import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {migrate} from '../src/infrastructure/sqlite/migrate.js';
import {createSpecimenPhysicsService} from '../src/application/specimen-physics.js';

function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());migrate(db);db.exec(`INSERT INTO companies VALUES('c1','شرکت یک'),('c2','شرکت دو');
 INSERT INTO sampling_series(id,company_id,kind,title,purpose,sampled_at,sampler_name,entered_by) VALUES('s1','c1','internal','آزمایش','کنترل','2026-09-01T08:00:00.000Z','الف','ب'),('s2','c2','internal','آزمایش','کنترل','2026-09-01T08:00:00.000Z','الف','ب');
 INSERT INTO samples VALUES('s1-7a','s1',7,'2026-09-08T08:00:00.000Z'),('s1-7b','s1',7,'2026-09-08T08:00:00.000Z'),('s1-28a','s1',28,'2026-09-29T08:00:00.000Z'),('s1-w','s1',NULL,NULL),('s2-7','s2',7,'2026-09-08T08:00:00.000Z');`);return{db,service:createSpecimenPhysicsService(db,{companyId:'c1',actor:'کاربر',clock:()=> '2026-09-10T10:00:00.000Z'})};}

test('each 7-day, 28-day and witness specimen stores its own physical measurement',t=>{const{service}=fixture(t);const a=service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.1});const b=service.save({sampleId:'s1-7b',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.0});const d28=service.save({sampleId:'s1-28a',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.2});const w=service.save({sampleId:'s1-w',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.05});assert.equal(a.densityKgM3,2400);assert.notEqual(a.densityKgM3,b.densityKgM3);assert.equal(service.get('s1-28a').mass_kg,8.2);assert.equal(service.get('s1-w').mass_kg,8.05);assert.equal(d28.revision,1);assert.equal(w.revision,1);});

test('cylinder volume and density are calculated deterministically in the service',t=>{const{service}=fixture(t);const r=service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cylinder',diameterMm:150,heightMm:300,massKg:12.5});const expectedVolume=Math.PI*0.075*0.075*0.3;assert.ok(Math.abs(r.volumeM3-expectedVolume)<1e-12);assert.ok(Math.abs(r.densityKgM3-(12.5/expectedVolume))<1e-9);});

test('physical measurement corrections are append-only and stale edits are rejected',t=>{const{db,service}=fixture(t);service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.1});assert.throws(()=>service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.2}),/تغییر کرده/);const revised=service.save({sampleId:'s1-7a',expectedRevision:1,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8.2,reason:'اصلاح وزن ثبت‌شده'});assert.equal(revised.revision,2);assert.equal(service.history('s1-7a').length,2);assert.throws(()=>db.exec("UPDATE specimen_physical_measurement_revisions SET mass_kg=9"));assert.throws(()=>db.exec('DELETE FROM specimen_physical_measurement_revisions'));});

test('specimen physics is company scoped and validates geometry inputs',t=>{const{service}=fixture(t);assert.throws(()=>service.save({sampleId:'s2-7',expectedRevision:0,shape:'cube',lengthMm:150,widthMm:150,heightMm:150,massKg:8}),/متعلق به این شرکت/);assert.throws(()=>service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cube',lengthMm:0,widthMm:150,heightMm:150,massKg:8}));assert.throws(()=>service.save({sampleId:'s1-7a',expectedRevision:0,shape:'cylinder',diameterMm:150,heightMm:0,massKg:8}));});
