import { app, BrowserWindow, dialog, ipcMain, type IpcMainInvokeEvent } from 'electron';
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import * as XLSX from 'xlsx';
import { projectReportWorkbook } from './project-report-workbook.js';
import { createDatabaseRuntime, type DatabaseRuntime } from './database.js';
import { IPC_CHANNELS, type AddAttachmentResult, type AnalyticsFilter, type AnalyticsSummary, type AppInfo, type ApproveDraftInput, type AttachmentSummary, type CreateConcreteSourceInput, type CreateCustomerInput, type CreateMixDesignInput, type CreateMixVersionInput, type CreatePourInput, type CreateProjectInput, type CreateSeriesInput, type CreateTestingLaboratoryInput, type DraftResult, type HealthStatus, type IpcResult, type LaboratoryKind, type ProjectQcReport, type ProjectQcReportInput, type RegisterExternalResultInput, type ReportExportResult, type RequestCorrectionInput, type SaveDraftInput, type SaveFreshConcreteInput, type SavePourContextInput, type SavePourSpecificationInput, type SaveSpecimenPhysicsInput, type ScheduleWitnessInput, type SeriesSummary, type CreateSeriesResult, type SampleSummary, type ApprovalResult, type ResultRevision, type VoidResultInput, type VoidResult, type WitnessScheduleResult, type WitnessScheduleRevision } from '../shared/ipc.js';
const require=createRequire(import.meta.url);
const handledSquirrelEvent=process.platform==='win32'&&Boolean(require('electron-squirrel-startup'));
if(handledSquirrelEvent)app.quit();
if(process.platform==='win32')app.setAppUserModelId('com.squirrel.tolou_concrete_qc.TolouConcreteQC');
const __dirname=dirname(fileURLToPath(import.meta.url)); let runtime:DatabaseRuntime|undefined;
function createMainWindow():BrowserWindow{const window=new BrowserWindow({width:1440,height:900,minWidth:1180,minHeight:720,show:false,backgroundColor:'#F5F6F8',title:'طلوع | کنترل کیفیت بتن',autoHideMenuBar:true,webPreferences:{preload:join(__dirname,'../preload/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,devTools:!app.isPackaged}});window.once('ready-to-show',()=>window.show());const devServer=process.env.VITE_DEV_SERVER_URL;if(devServer)void window.loadURL(devServer);else void window.loadFile(join(__dirname,'../../dist-renderer/index.html'));window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(event,url)=>{if(!devServer||!url.startsWith(devServer))event.preventDefault();});return window;}
function safeMessage(error:unknown):string{if(error instanceof Error){console.error('[Tolou IPC]',error);const message=error.message.trim();if(message.length<=180&&/[\u0600-\u06FF]/u.test(message)&&!/SQLITE|constraint|FOREIGN KEY|UNIQUE|CHECK|trigger|database|syntax|stack/i.test(message))return message;}return 'عملیات انجام نشد. اطلاعات ورودی را بررسی کنید و دوباره تلاش کنید.';}
function safe<T>(operation:()=>T):IpcResult<T>{try{return{ok:true,data:operation()};}catch(error){return{ok:false,message:safeMessage(error)};}}
type TrustedIpcHandler=(event:IpcMainInvokeEvent,...args:any[])=>any;
function isTrustedIpcSender(event:IpcMainInvokeEvent):boolean{const frame=event.senderFrame;if(!frame||frame!==event.sender.mainFrame)return false;const window=BrowserWindow.fromWebContents(event.sender);if(!window)return false;const devServer=process.env.VITE_DEV_SERVER_URL;if(devServer)return frame.url.startsWith(devServer);try{return new URL(frame.url).protocol==='file:';}catch{return false;}}
function handleTrustedIpc(channel:string,handler:TrustedIpcHandler):void{ipcMain.handle(channel,(event,...args)=>{if(!isTrustedIpcSender(event)){console.warn('[Tolou IPC] Rejected untrusted sender',channel,event.senderFrame?.url??'<destroyed>');throw new Error('IPC sender rejected');}return handler(event,...args);});}
function safeFileName(value:string){return(value||'tolou-qc-report').replace(/[<>:"/\\|?*\x00-\x1F]/g,'-').trim()||'tolou-qc-report';}
function registerIpc(database:DatabaseRuntime):void{
 handleTrustedIpc(IPC_CHANNELS.appInfo,():AppInfo=>({name:app.getName(),version:app.getVersion(),platform:process.platform,locale:app.getLocale()}));handleTrustedIpc(IPC_CHANNELS.health,():HealthStatus=>({ok:true,timestamp:new Date().toISOString(),database:'ready'}));
 handleTrustedIpc(IPC_CHANNELS.createSeries,(_e,input:CreateSeriesInput):IpcResult<CreateSeriesResult>=>safe(()=>database.laboratory.createSeries(input) as CreateSeriesResult));handleTrustedIpc(IPC_CHANNELS.listSeries,(_e,input:{kind:LaboratoryKind;projectId?:string}):IpcResult<SeriesSummary[]>=>safe(()=>database.laboratory.listSeries(input) as SeriesSummary[]));handleTrustedIpc(IPC_CHANNELS.saveDraft,(_e,input:SaveDraftInput):IpcResult<DraftResult>=>safe(()=>database.laboratory.saveDraft(input) as DraftResult));handleTrustedIpc(IPC_CHANNELS.listSamples,(_e,limit?:number):IpcResult<SampleSummary[]>=>safe(()=>database.laboratory.listSamples({limit}) as SampleSummary[]));handleTrustedIpc(IPC_CHANNELS.approveDraft,(_e,input:ApproveDraftInput):IpcResult<ApprovalResult>=>safe(()=>database.laboratory.approveDraft(input) as ApprovalResult));handleTrustedIpc(IPC_CHANNELS.requestCorrection,(_e,input:RequestCorrectionInput):IpcResult<DraftResult>=>safe(()=>database.laboratory.requestCorrection(input) as DraftResult));handleTrustedIpc(IPC_CHANNELS.voidResult,(_e,input:VoidResultInput):IpcResult<VoidResult>=>safe(()=>database.laboratory.voidResult(input) as VoidResult));handleTrustedIpc(IPC_CHANNELS.reviewQueue,(_e,limit?:number):IpcResult<SampleSummary[]>=>safe(()=>database.laboratory.listReviewQueue({limit}) as SampleSummary[]));handleTrustedIpc(IPC_CHANNELS.resultHistory,(_e,sampleId:string):IpcResult<ResultRevision[]>=>safe(()=>database.laboratory.listResultHistory(sampleId) as ResultRevision[]));handleTrustedIpc(IPC_CHANNELS.scheduleWitness,(_e,input:ScheduleWitnessInput):IpcResult<WitnessScheduleResult>=>safe(()=>database.laboratory.scheduleWitness(input) as WitnessScheduleResult));handleTrustedIpc(IPC_CHANNELS.witnessScheduleHistory,(_e,sampleId:string):IpcResult<WitnessScheduleRevision[]>=>safe(()=>database.laboratory.listWitnessScheduleHistory(sampleId) as WitnessScheduleRevision[]));
 handleTrustedIpc(IPC_CHANNELS.createProject,(_e,input:CreateProjectInput)=>safe(()=>database.projects.createProject(input)));handleTrustedIpc(IPC_CHANNELS.listProjects,()=>safe(()=>database.projects.listProjects()));handleTrustedIpc(IPC_CHANNELS.createPour,(_e,input:CreatePourInput)=>safe(()=>database.projects.createPour(input)));handleTrustedIpc(IPC_CHANNELS.listPours,(_e,projectId:string)=>safe(()=>database.projects.listPours(projectId)));handleTrustedIpc(IPC_CHANNELS.dashboard,()=>safe(()=>database.projects.dashboard()));handleTrustedIpc(IPC_CHANNELS.savePourContext,(_e,input:SavePourContextInput)=>safe(()=>database.pourContext.save(input)));handleTrustedIpc(IPC_CHANNELS.getPourContext,(_e,pourId:string)=>safe(()=>database.pourContext.get(pourId)));handleTrustedIpc(IPC_CHANNELS.listPourContexts,(_e,projectId?:string)=>safe(()=>database.pourContext.list(projectId)));
 handleTrustedIpc(IPC_CHANNELS.createMixDesign,(_e,input:CreateMixDesignInput)=>safe(()=>database.engineering.createMixDesign(input)));handleTrustedIpc(IPC_CHANNELS.listMixDesigns,()=>safe(()=>database.engineering.listMixDesigns()));handleTrustedIpc(IPC_CHANNELS.createMixVersion,(_e,input:CreateMixVersionInput)=>safe(()=>database.engineering.createMixVersion(input)));handleTrustedIpc(IPC_CHANNELS.listMixVersions,(_e,mixDesignId:string)=>safe(()=>database.engineering.listMixVersions(mixDesignId)));handleTrustedIpc(IPC_CHANNELS.savePourSpecification,(_e,input:SavePourSpecificationInput)=>safe(()=>database.engineering.savePourSpecification(input)));handleTrustedIpc(IPC_CHANNELS.getPourSpecification,(_e,pourId:string)=>safe(()=>database.engineering.getPourSpecification(pourId)));
 handleTrustedIpc(IPC_CHANNELS.createCustomer,(_e,input:CreateCustomerInput)=>safe(()=>database.qcParties.createCustomer(input)));handleTrustedIpc(IPC_CHANNELS.listCustomers,()=>safe(()=>database.qcParties.listCustomers()));handleTrustedIpc(IPC_CHANNELS.createConcreteSource,(_e,input:CreateConcreteSourceInput)=>safe(()=>database.qcParties.createConcreteSource(input)));handleTrustedIpc(IPC_CHANNELS.listConcreteSources,()=>safe(()=>database.qcParties.listConcreteSources()));handleTrustedIpc(IPC_CHANNELS.createTestingLaboratory,(_e,input:CreateTestingLaboratoryInput)=>safe(()=>database.qcParties.createTestingLaboratory(input)));handleTrustedIpc(IPC_CHANNELS.listTestingLaboratories,()=>safe(()=>database.qcParties.listTestingLaboratories()));handleTrustedIpc(IPC_CHANNELS.registerExternalResult,(_e,input:RegisterExternalResultInput)=>safe(()=>database.qcParties.registerExternalResult(input)));handleTrustedIpc(IPC_CHANNELS.listExternalResults,(_e,limit?:number)=>safe(()=>database.qcParties.listExternalResults({limit})));
 handleTrustedIpc(IPC_CHANNELS.listExternalAttachments,(_e,eventId:string):IpcResult<AttachmentSummary[]>=>safe(()=>database.attachments.list(eventId) as AttachmentSummary[]));handleTrustedIpc(IPC_CHANNELS.addExternalAttachment,async(_e,eventId:string):Promise<IpcResult<AddAttachmentResult>>=>{try{const selection=await dialog.showOpenDialog({title:'انتخاب پیوست نتیجه خارجی',properties:['openFile'],filters:[{name:'گزارش‌ها و اسناد',extensions:['pdf','png','jpg','jpeg','webp','csv','txt']},{name:'همه فایل‌ها',extensions:['*']}]});if(selection.canceled||selection.filePaths.length===0)return{ok:true,data:{cancelled:true}};const attachment=database.attachments.addFromPath(eventId,selection.filePaths[0]);return{ok:true,data:{cancelled:false,attachment}};}catch(error){return{ok:false,message:safeMessage(error)};}});
 handleTrustedIpc(IPC_CHANNELS.saveSpecimenPhysics,(_e,input:SaveSpecimenPhysicsInput)=>safe(()=>database.specimenPhysics.save(input)));handleTrustedIpc(IPC_CHANNELS.getSpecimenPhysics,(_e,sampleId:string)=>safe(()=>database.specimenPhysics.get(sampleId)));handleTrustedIpc(IPC_CHANNELS.listSpecimenPhysics,(_e,limit?:number)=>safe(()=>database.specimenPhysics.listCurrent({limit})));handleTrustedIpc(IPC_CHANNELS.specimenPhysicsHistory,(_e,sampleId:string)=>safe(()=>database.specimenPhysics.history(sampleId)));handleTrustedIpc(IPC_CHANNELS.saveFreshConcrete,(_e,input:SaveFreshConcreteInput)=>safe(()=>database.freshConcrete.save(input)));handleTrustedIpc(IPC_CHANNELS.getFreshConcrete,(_e,seriesId:string)=>safe(()=>database.freshConcrete.get(seriesId)));handleTrustedIpc(IPC_CHANNELS.freshConcreteHistory,(_e,seriesId:string)=>safe(()=>database.freshConcrete.history(seriesId)));handleTrustedIpc(IPC_CHANNELS.analyticsSummary,(_e,input:AnalyticsFilter={}):IpcResult<AnalyticsSummary>=>safe(()=>database.analytics.summary(input) as AnalyticsSummary));handleTrustedIpc(IPC_CHANNELS.projectQcReport,(_e,input:ProjectQcReportInput):IpcResult<ProjectQcReport>=>safe(()=>database.reporting.projectQc(input) as ProjectQcReport));
 handleTrustedIpc(IPC_CHANNELS.exportProjectQcPdf,async(event,suggestedName:string):Promise<IpcResult<ReportExportResult>>=>{try{const window=BrowserWindow.fromWebContents(event.sender);if(!window)throw new Error('پنجره گزارش در دسترس نیست');const selection=await dialog.showSaveDialog(window,{title:'ذخیره گزارش PDF',defaultPath:`${safeFileName(suggestedName)}.pdf`,filters:[{name:'PDF',extensions:['pdf']}]});if(selection.canceled||!selection.filePath)return{ok:true,data:{cancelled:true}};const pdf=await event.sender.printToPDF({pageSize:'A4',landscape:false,printBackground:true,preferCSSPageSize:true,displayHeaderFooter:false,margins:{top:0.35,bottom:0.35,left:0.35,right:0.35}});await writeFile(selection.filePath,pdf);return{ok:true,data:{cancelled:false,path:selection.filePath}};}catch(error){console.error('[Tolou PDF export]',error);return{ok:false,message:'ذخیره گزارش PDF انجام نشد.'};}});
 handleTrustedIpc(IPC_CHANNELS.exportProjectQcExcel,async(event,input:ProjectQcReportInput,suggestedName:string):Promise<IpcResult<ReportExportResult>>=>{try{const report=database.reporting.projectQc(input) as ProjectQcReport;const window=BrowserWindow.fromWebContents(event.sender);if(!window)throw new Error('پنجره گزارش در دسترس نیست');const selection=await dialog.showSaveDialog(window,{title:'ذخیره گزارش Excel',defaultPath:`${safeFileName(suggestedName)}.xlsx`,filters:[{name:'Excel Workbook',extensions:['xlsx']}]});if(selection.canceled||!selection.filePath)return{ok:true,data:{cancelled:true}};const workbook=projectReportWorkbook(report);const bytes=XLSX.write(workbook,{bookType:'xlsx',type:'buffer',compression:true});await writeFile(selection.filePath,bytes);return{ok:true,data:{cancelled:false,path:selection.filePath}};}catch(error){console.error('[Tolou Excel export]',error);return{ok:false,message:safeMessage(error)};}});
}
app.whenReady().then(()=>{runtime=createDatabaseRuntime();registerIpc(runtime);createMainWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createMainWindow();});});app.on('before-quit',()=>{runtime?.db.close();runtime=undefined;});app.on('window-all-closed',()=>app.quit());
