import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDatabaseRuntime, type DatabaseRuntime } from './database.js';
import { IPC_CHANNELS, type AddAttachmentResult, type AnalyticsFilter, type AnalyticsSummary, type AppInfo, type ApproveDraftInput, type AttachmentSummary, type CreateConcreteSourceInput, type CreateCustomerInput, type CreateMixDesignInput, type CreateMixVersionInput, type CreatePourInput, type CreateProjectInput, type CreateSeriesInput, type CreateTestingLaboratoryInput, type DraftResult, type HealthStatus, type IpcResult, type LaboratoryKind, type ProjectQcReport, type ProjectQcReportInput, type RegisterExternalResultInput, type RequestCorrectionInput, type SaveDraftInput, type SaveFreshConcreteInput, type SavePourContextInput, type SavePourSpecificationInput, type SaveSpecimenPhysicsInput, type ScheduleWitnessInput, type SeriesSummary, type CreateSeriesResult, type SampleSummary, type ApprovalResult, type ResultRevision, type VoidResultInput, type VoidResult, type WitnessScheduleResult, type WitnessScheduleRevision } from '../shared/ipc.js';
const __dirname=dirname(fileURLToPath(import.meta.url)); let runtime:DatabaseRuntime|undefined;
function createMainWindow():BrowserWindow{const window=new BrowserWindow({width:1440,height:900,minWidth:1180,minHeight:720,show:false,backgroundColor:'#F5F6F8',title:'طلوع | کنترل کیفیت بتن',autoHideMenuBar:true,webPreferences:{preload:join(__dirname,'../preload/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,devTools:!app.isPackaged}});window.once('ready-to-show',()=>window.show());const devServer=process.env.VITE_DEV_SERVER_URL;if(devServer)void window.loadURL(devServer);else void window.loadFile(join(__dirname,'../../dist-renderer/index.html'));window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',(event,url)=>{if(!devServer||!url.startsWith(devServer))event.preventDefault();});return window;}
function safeMessage(error:unknown):string{if(error instanceof Error){console.error('[Tolou IPC]',error);const message=error.message.trim();if(message.length<=180&&/[\u0600-\u06FF]/u.test(message)&&!/SQLITE|constraint|FOREIGN KEY|UNIQUE|CHECK|trigger|database|syntax|stack/i.test(message))return message;}return 'عملیات انجام نشد. اطلاعات ورودی را بررسی کنید و دوباره تلاش کنید.';}
function safe<T>(operation:()=>T):IpcResult<T>{try{return{ok:true,data:operation()};}catch(error){return{ok:false,message:safeMessage(error)};}}
function registerIpc(database:DatabaseRuntime):void{
 ipcMain.handle(IPC_CHANNELS.appInfo,():AppInfo=>({name:app.getName(),version:app.getVersion(),platform:process.platform,locale:app.getLocale()}));ipcMain.handle(IPC_CHANNELS.health,():HealthStatus=>({ok:true,timestamp:new Date().toISOString(),database:'ready'}));
 ipcMain.handle(IPC_CHANNELS.createSeries,(_e,input:CreateSeriesInput):IpcResult<CreateSeriesResult>=>safe(()=>database.laboratory.createSeries(input) as CreateSeriesResult));ipcMain.handle(IPC_CHANNELS.listSeries,(_e,input:{kind:LaboratoryKind;projectId?:string}):IpcResult<SeriesSummary[]>=>safe(()=>database.laboratory.listSeries(input) as SeriesSummary[]));ipcMain.handle(IPC_CHANNELS.saveDraft,(_e,input:SaveDraftInput):IpcResult<DraftResult>=>safe(()=>database.laboratory.saveDraft(input) as DraftResult));ipcMain.handle(IPC_CHANNELS.listSamples,(_e,limit?:number):IpcResult<SampleSummary[]>=>safe(()=>database.laboratory.listSamples({limit}) as SampleSummary[]));ipcMain.handle(IPC_CHANNELS.approveDraft,(_e,input:ApproveDraftInput):IpcResult<ApprovalResult>=>safe(()=>database.laboratory.approveDraft(input) as ApprovalResult));ipcMain.handle(IPC_CHANNELS.requestCorrection,(_e,input:RequestCorrectionInput):IpcResult<DraftResult>=>safe(()=>database.laboratory.requestCorrection(input) as DraftResult));ipcMain.handle(IPC_CHANNELS.voidResult,(_e,input:VoidResultInput):IpcResult<VoidResult>=>safe(()=>database.laboratory.voidResult(input) as VoidResult));ipcMain.handle(IPC_CHANNELS.reviewQueue,(_e,limit?:number):IpcResult<SampleSummary[]>=>safe(()=>database.laboratory.listReviewQueue({limit}) as SampleSummary[]));ipcMain.handle(IPC_CHANNELS.resultHistory,(_e,sampleId:string):IpcResult<ResultRevision[]>=>safe(()=>database.laboratory.listResultHistory(sampleId) as ResultRevision[]));ipcMain.handle(IPC_CHANNELS.scheduleWitness,(_e,input:ScheduleWitnessInput):IpcResult<WitnessScheduleResult>=>safe(()=>database.laboratory.scheduleWitness(input) as WitnessScheduleResult));ipcMain.handle(IPC_CHANNELS.witnessScheduleHistory,(_e,sampleId:string):IpcResult<WitnessScheduleRevision[]>=>safe(()=>database.laboratory.listWitnessScheduleHistory(sampleId) as WitnessScheduleRevision[]));
 ipcMain.handle(IPC_CHANNELS.createProject,(_e,input:CreateProjectInput)=>safe(()=>database.projects.createProject(input)));ipcMain.handle(IPC_CHANNELS.listProjects,()=>safe(()=>database.projects.listProjects()));ipcMain.handle(IPC_CHANNELS.createPour,(_e,input:CreatePourInput)=>safe(()=>database.projects.createPour(input)));ipcMain.handle(IPC_CHANNELS.listPours,(_e,projectId:string)=>safe(()=>database.projects.listPours(projectId)));ipcMain.handle(IPC_CHANNELS.dashboard,()=>safe(()=>database.projects.dashboard()));ipcMain.handle(IPC_CHANNELS.savePourContext,(_e,input:SavePourContextInput)=>safe(()=>database.pourContext.save(input)));ipcMain.handle(IPC_CHANNELS.getPourContext,(_e,pourId:string)=>safe(()=>database.pourContext.get(pourId)));ipcMain.handle(IPC_CHANNELS.listPourContexts,(_e,projectId?:string)=>safe(()=>database.pourContext.list(projectId)));
 ipcMain.handle(IPC_CHANNELS.createMixDesign,(_e,input:CreateMixDesignInput)=>safe(()=>database.engineering.createMixDesign(input)));ipcMain.handle(IPC_CHANNELS.listMixDesigns,()=>safe(()=>database.engineering.listMixDesigns()));ipcMain.handle(IPC_CHANNELS.createMixVersion,(_e,input:CreateMixVersionInput)=>safe(()=>database.engineering.createMixVersion(input)));ipcMain.handle(IPC_CHANNELS.listMixVersions,(_e,mixDesignId:string)=>safe(()=>database.engineering.listMixVersions(mixDesignId)));ipcMain.handle(IPC_CHANNELS.savePourSpecification,(_e,input:SavePourSpecificationInput)=>safe(()=>database.engineering.savePourSpecification(input)));ipcMain.handle(IPC_CHANNELS.getPourSpecification,(_e,pourId:string)=>safe(()=>database.engineering.getPourSpecification(pourId)));
 ipcMain.handle(IPC_CHANNELS.createCustomer,(_e,input:CreateCustomerInput)=>safe(()=>database.qcParties.createCustomer(input)));ipcMain.handle(IPC_CHANNELS.listCustomers,()=>safe(()=>database.qcParties.listCustomers()));ipcMain.handle(IPC_CHANNELS.createConcreteSource,(_e,input:CreateConcreteSourceInput)=>safe(()=>database.qcParties.createConcreteSource(input)));ipcMain.handle(IPC_CHANNELS.listConcreteSources,()=>safe(()=>database.qcParties.listConcreteSources()));ipcMain.handle(IPC_CHANNELS.createTestingLaboratory,(_e,input:CreateTestingLaboratoryInput)=>safe(()=>database.qcParties.createTestingLaboratory(input)));ipcMain.handle(IPC_CHANNELS.listTestingLaboratories,()=>safe(()=>database.qcParties.listTestingLaboratories()));ipcMain.handle(IPC_CHANNELS.registerExternalResult,(_e,input:RegisterExternalResultInput)=>safe(()=>database.qcParties.registerExternalResult(input)));ipcMain.handle(IPC_CHANNELS.listExternalResults,(_e,limit?:number)=>safe(()=>database.qcParties.listExternalResults({limit})));
 ipcMain.handle(IPC_CHANNELS.listExternalAttachments,(_e,eventId:string):IpcResult<AttachmentSummary[]>=>safe(()=>database.attachments.list(eventId) as AttachmentSummary[]));ipcMain.handle(IPC_CHANNELS.addExternalAttachment,async(_e,eventId:string):Promise<IpcResult<AddAttachmentResult>>=>{try{const selection=await dialog.showOpenDialog({title:'انتخاب پیوست نتیجه خارجی',properties:['openFile'],filters:[{name:'گزارش‌ها و اسناد',extensions:['pdf','png','jpg','jpeg','webp','csv','txt']},{name:'همه فایل‌ها',extensions:['*']}]});if(selection.canceled||selection.filePaths.length===0)return{ok:true,data:{cancelled:true}};const attachment=database.attachments.addFromPath(eventId,selection.filePaths[0]);return{ok:true,data:{cancelled:false,attachment}};}catch(error){return{ok:false,message:safeMessage(error)};}});
 ipcMain.handle(IPC_CHANNELS.saveSpecimenPhysics,(_e,input:SaveSpecimenPhysicsInput)=>safe(()=>database.specimenPhysics.save(input)));ipcMain.handle(IPC_CHANNELS.getSpecimenPhysics,(_e,sampleId:string)=>safe(()=>database.specimenPhysics.get(sampleId)));ipcMain.handle(IPC_CHANNELS.listSpecimenPhysics,(_e,limit?:number)=>safe(()=>database.specimenPhysics.listCurrent({limit})));ipcMain.handle(IPC_CHANNELS.specimenPhysicsHistory,(_e,sampleId:string)=>safe(()=>database.specimenPhysics.history(sampleId)));ipcMain.handle(IPC_CHANNELS.saveFreshConcrete,(_e,input:SaveFreshConcreteInput)=>safe(()=>database.freshConcrete.save(input)));ipcMain.handle(IPC_CHANNELS.getFreshConcrete,(_e,seriesId:string)=>safe(()=>database.freshConcrete.get(seriesId)));ipcMain.handle(IPC_CHANNELS.freshConcreteHistory,(_e,seriesId:string)=>safe(()=>database.freshConcrete.history(seriesId)));ipcMain.handle(IPC_CHANNELS.analyticsSummary,(_e,input:AnalyticsFilter={}):IpcResult<AnalyticsSummary>=>safe(()=>database.analytics.summary(input) as AnalyticsSummary));ipcMain.handle(IPC_CHANNELS.projectQcReport,(_e,input:ProjectQcReportInput):IpcResult<ProjectQcReport>=>safe(()=>database.reporting.projectQc(input) as ProjectQcReport));
}
app.whenReady().then(()=>{runtime=createDatabaseRuntime();registerIpc(runtime);createMainWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createMainWindow();});});app.on('before-quit',()=>{runtime?.db.close();runtime=undefined;});app.on('window-all-closed',()=>app.quit());
