import * as XLSX from 'xlsx';
import type { ProjectQcReport } from '../shared/ipc.js';

type EngineeringContext={elementName:string;concreteClass:string;specifiedStrengthMpa:number|null;projectCharacteristicStrengthMpa:number|null;targetSlumpMm:number|null;mixCode:string|null;mixTitle:string|null;mixRevision:number|null;reference7Mpa:number|null;reference28Mpa:number|null;attainment7Percent:number|null;attainment28Percent:number|null};
type DetailedSpecimen={id:string;ageDays:number|null;dueAt:string|null;state:string|null;strengthMpa:number|null;testedAt:string|null;testedBy:string|null;approvedBy:string|null;shape:'cube'|'cylinder'|null;lengthMm:number|null;widthMm:number|null;heightMm:number|null;diameterMm:number|null;massKg:number|null;volumeM3:number|null;densityKgM3:number|null};
type DetailedSeries={id:string;sampledAt:string;samplerName:string;title:string;pourId:string|null;pourOccurredAt:string|null;concreteSourceName:string;engineeringContext:EngineeringContext|null;freshConcrete:{slumpMm:number|null;temperatureC:number|null;measuredAt:string|null};specimens:DetailedSpecimen[];summary:{mean7Mpa:number|null;mean28Mpa:number|null;approved7Count:number;approved28Count:number}};
type CanonicalRow={seriesId:string;sampledAt:string;samplerName:string;pourId:string|null;projectId:string|null;customerName:string;sourceName:string;elementName:string;concreteClass:string;mixCode:string|null;mixTitle:string|null;mixRevision:number|null;specifiedStrengthMpa:number|null;projectCharacteristicStrengthMpa:number|null;reference7Mpa:number|null;reference28Mpa:number|null;targetSlumpMm:number|null;slumpMm:number|null;temperatureC:number|null;mean7Mpa:number|null;mean28Mpa:number|null;attainment7Percent:number|null;attainment28Percent:number|null;sd28:number|null;cv28:number|null;densityMeanKgM3:number|null;approvedCount:number;draftCount:number;pendingCount:number;overdueCount:number;status:string};
type DetailedReport=ProjectQcReport&{generatedAt?:string;organization?:{qcManagerName?:string;managingDirectorName?:string};series?:DetailedSeries[];qcDataset?:CanonicalRow[]};
const status=(value:string|null)=>value==='approved'?'تأییدشده':value==='draft'?'پیش‌نویس':value==='void'?'باطل':'بدون نتیجه';

export function projectReportWorkbook(report:ProjectQcReport){
  const enriched=report as DetailedReport;
  const wb=XLSX.utils.book_new();
  const metrics=[['شاخص','واحد','تعداد','میانگین','انحراف معیار نمونه','CV %','کمینه','بیشینه'],...[[report.analytics.strength,'مقاومت فشاری'],[report.analytics.slump,'اسلامپ بتن تازه'],[report.analytics.concreteTemperature,'دمای بتن تازه'],[report.analytics.hardenedDensity,'جرم حجمی بتن سخت‌شده']].map(([raw,label])=>{const metric=raw as typeof report.analytics.slump,s=metric.statistics;return[label,metric.unit,s.count,s.mean,s.sampleSd,s.cvPercent,s.min,s.max];})];
  const summary=XLSX.utils.aoa_to_sheet([['سامانه طلوع | گزارش رسمی کنترل کیفیت بتن'],['شرکت',report.company.name],['مسئول کنترل کیفیت',enriched.organization?.qcManagerName||'—'],['مدیرعامل',enriched.organization?.managingDirectorName||'—'],['پروژه',report.project.name],['مشتری',report.project.customerName||'—'],['نشانی',report.project.address||'—'],['تاریخ صدور',enriched.generatedAt||'—'],['شروع بازه',report.filters.startAt||'—'],['پایان بازه',report.filters.endAt||'—'],['نوبت‌های نمونه‌برداری',report.counts.samplingSeries],['نتایج مقاومت تأییدشده',report.counts.approvedStrengthResults],['منبع محاسبات','Canonical QC Dataset'],[],...metrics,[],['Rule Profile',report.standards.profile??'—'],['ارزیابی قبولی/رد',report.standards.acceptanceEvaluated?'بله':'خیر'],...report.notes.map(note=>['یادداشت',note])]);
  summary['!cols']=[{wch:32},{wch:42},{wch:16},{wch:16},{wch:20},{wch:14},{wch:14},{wch:14}];
  XLSX.utils.book_append_sheet(wb,summary,'خلاصه مدیریتی');

  const canonicalRows:any[][]=[['Series ID','تاریخ نمونه‌برداری','Pour ID','مشتری','منبع بتن','عضو/محل','رده بتن','طرح','Revision','fck پروژه MPa','مقاومت مشخص‌شده Pour MPa','مرجع 7d MPa','میانگین 7d MPa','تحقق 7d %','مرجع 28d MPa','میانگین 28d MPa','تحقق 28d %','اسلامپ هدف mm','اسلامپ واقعی mm','دمای بتن °C','SD 28d','CV 28d %','میانگین جرم حجمی kg/m³','Approved','Draft','Pending','Overdue','وضعیت']];
  for(const row of enriched.qcDataset??[]){canonicalRows.push([row.seriesId,row.sampledAt,row.pourId??'',row.customerName||'',row.sourceName||'',row.elementName||'',row.concreteClass||'',row.mixCode?`${row.mixCode}${row.mixTitle?` — ${row.mixTitle}`:''}`:'',row.mixRevision,row.projectCharacteristicStrengthMpa,row.specifiedStrengthMpa,row.reference7Mpa,row.mean7Mpa,row.attainment7Percent,row.reference28Mpa,row.mean28Mpa,row.attainment28Percent,row.targetSlumpMm,row.slumpMm,row.temperatureC,row.sd28,row.cv28,row.densityMeanKgM3,row.approvedCount,row.draftCount,row.pendingCount,row.overdueCount,row.status]);}
  const canonical=XLSX.utils.aoa_to_sheet(canonicalRows);canonical['!cols']=[{wch:24},{wch:24},{wch:22},{wch:22},{wch:22},{wch:22},{wch:14},{wch:28},{wch:10},{wch:16},{wch:22},{wch:16},{wch:16},{wch:14},{wch:16},{wch:16},{wch:14},{wch:16},{wch:16},{wch:14},{wch:14},{wch:14},{wch:22},{wch:10},{wch:10},{wch:10},{wch:10},{wch:14}];XLSX.utils.book_append_sheet(wb,canonical,'Master QC Dataset');

  const detailRows:any[][]=[['ردیف','تاریخ نمونه‌برداری','نمونه‌بردار','منبع بتن','عضو/محل','رده بتن','طرح/Revision','fck پروژه MPa','مرجع سن MPa','اسلامپ mm','دمای بتن °C','سن روز','موعد آزمون','شکل','طول mm','عرض mm','ارتفاع mm','قطر mm','جرم kg','حجم m³','جرم حجمی kg/m³','مقاومت MPa','زمان آزمون','آزمایش‌کننده','تأییدکننده','وضعیت']];
  let rowNo=1;
  for(const series of enriched.series??[]){const ec=series.engineeringContext;for(const specimen of series.specimens){const reference=specimen.ageDays===7?ec?.reference7Mpa??null:specimen.ageDays===28?ec?.reference28Mpa??null:null;detailRows.push([rowNo++,series.sampledAt,series.samplerName,series.concreteSourceName||'',ec?.elementName||'',ec?.concreteClass||'',ec?.mixCode?`${ec.mixCode}${ec.mixRevision!==null?` / R${ec.mixRevision}`:''}`:'',ec?.projectCharacteristicStrengthMpa??null,reference,series.freshConcrete.slumpMm,series.freshConcrete.temperatureC,specimen.ageDays??'شاهد',specimen.dueAt,specimen.shape==='cube'?'مکعبی':specimen.shape==='cylinder'?'استوانه‌ای':'',specimen.lengthMm,specimen.widthMm,specimen.heightMm,specimen.diameterMm,specimen.massKg,specimen.volumeM3,specimen.densityKgM3,specimen.strengthMpa,specimen.testedAt,specimen.testedBy||'',specimen.approvedBy||'',status(specimen.state)]);}}
  const details=XLSX.utils.aoa_to_sheet(detailRows);details['!cols']=[{wch:8},{wch:24},{wch:20},{wch:22},{wch:22},{wch:14},{wch:24},{wch:16},{wch:16},{wch:12},{wch:14},{wch:10},{wch:24},{wch:12},{wch:12},{wch:12},{wch:12},{wch:12},{wch:12},{wch:14},{wch:20},{wch:16},{wch:24},{wch:20},{wch:20},{wch:14}];XLSX.utils.book_append_sheet(wb,details,'ریز نتایج آزمون');

  const seriesRows:any[][]=[['نوبت','تاریخ نمونه‌برداری','نمونه‌بردار','منبع بتن','عضو/محل','رده بتن','طرح/Revision','fck پروژه MPa','اسلامپ هدف mm','اسلامپ واقعی mm','دمای بتن °C','تعداد تأییدشده ۷ روزه','مرجع ۷ روزه MPa','میانگین ۷ روزه MPa','تحقق ۷ روزه %','تعداد تأییدشده ۲۸ روزه','مرجع ۲۸ روزه MPa','میانگین ۲۸ روزه MPa','تحقق ۲۸ روزه %']];
  (enriched.series??[]).forEach((s,i)=>{const ec=s.engineeringContext;seriesRows.push([i+1,s.sampledAt,s.samplerName,s.concreteSourceName||'',ec?.elementName||'',ec?.concreteClass||'',ec?.mixCode?`${ec.mixCode}${ec.mixRevision!==null?` / R${ec.mixRevision}`:''}`:'',ec?.projectCharacteristicStrengthMpa??null,ec?.targetSlumpMm??null,s.freshConcrete.slumpMm,s.freshConcrete.temperatureC,s.summary.approved7Count,ec?.reference7Mpa??null,s.summary.mean7Mpa,ec?.attainment7Percent??null,s.summary.approved28Count,ec?.reference28Mpa??null,s.summary.mean28Mpa,ec?.attainment28Percent??null]);});
  const seriesSheet=XLSX.utils.aoa_to_sheet(seriesRows);seriesSheet['!cols']=[{wch:8},{wch:24},{wch:20},{wch:22},{wch:22},{wch:14},{wch:24},{wch:16},{wch:16},{wch:16},{wch:14},{wch:20},{wch:18},{wch:20},{wch:18},{wch:22},{wch:18},{wch:22},{wch:18}];XLSX.utils.book_append_sheet(wb,seriesSheet,'خلاصه نوبت‌های نمونه‌گیری');

  const trendSheet=XLSX.utils.aoa_to_sheet([['شاخص','زمان UTC','مقدار','واحد','سری نمونه‌گیری','نمونه','پروژه','سن روز'],...[[report.analytics.strength,'مقاومت فشاری'],[report.analytics.slump,'اسلامپ'],[report.analytics.concreteTemperature,'دمای بتن'],[report.analytics.hardenedDensity,'جرم حجمی']].flatMap(([raw,label])=>{const metric=raw as typeof report.analytics.slump;return metric.trend.map(p=>[label,p.at,p.value,metric.unit,p.seriesId??'',p.sampleId??'',p.projectId??'',p.ageDays??'']);})]);
  trendSheet['!cols']=[{wch:22},{wch:26},{wch:14},{wch:14},{wch:22},{wch:22},{wch:22},{wch:10}];XLSX.utils.book_append_sheet(wb,trendSheet,'داده‌های روند');
  const ageSheet=XLSX.utils.aoa_to_sheet([['سن روز','تعداد','میانگین MPa','SD','CV %','کمینه','بیشینه'],...Object.entries(report.analytics.strength.byAge).map(([age,s])=>[age,s.count,s.mean,s.sampleSd,s.cvPercent,s.min,s.max])]);ageSheet['!cols']=[{wch:12},{wch:12},{wch:18},{wch:14},{wch:14},{wch:14},{wch:14}];XLSX.utils.book_append_sheet(wb,ageSheet,'مقاومت برحسب سن');
  return wb;
}
