const text=(value,label)=>{if(typeof value!=='string'||!value.trim())throw new Error(`${label} الزامی است`);return value.trim();};
const optionalText=(value)=>typeof value==='string'?value.trim():'';
const optionalStrength=(value)=>{if(value==null||value==='')return null;if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>=1e308)throw new Error('مقاومت معتبر وارد کنید');return value;};
const optionalUtc=(value,label)=>{if(value==null||value==='')return null;if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value))throw new Error(`${label} معتبر نیست`);const d=new Date(value);if(!Number.isFinite(d.getTime())||d.toISOString()!==value)throw new Error(`${label} معتبر نیست`);return value;};
export function createQcPartiesService(db,{companyId,actor,clock=()=>new Date().toISOString()}){
 companyId=text(companyId,'شرکت');actor=text(actor,'کاربر فعال');
 const list=(table)=>db.prepare(`SELECT id,code,name,archived FROM ${table} WHERE company_id=? ORDER BY archived,code,name`).all(companyId);
 const createParty=(table,input,typeColumn,typeValue)=>{const id=text(input?.id,'شناسه');const code=text(input?.code,'کد');const name=text(input?.name,'نام');if(db.prepare(`SELECT id FROM ${table} WHERE id=?`).get(id))throw new Error('این شناسه قبلاً ثبت شده است');if(db.prepare(`SELECT id FROM ${table} WHERE company_id=? AND code=?`).get(companyId,code))throw new Error('این کد قبلاً در شرکت ثبت شده است');if(typeColumn)db.prepare(`INSERT INTO ${table}(id,company_id,code,name,${typeColumn}) VALUES(?,?,?,?,?)`).run(id,companyId,code,name,typeValue);else db.prepare(`INSERT INTO ${table}(id,company_id,code,name) VALUES(?,?,?,?)`).run(id,companyId,code,name);return{id,code,name};};
 return{
  createCustomer:(input)=>createParty('customers',input),listCustomers:()=>list('customers'),
  createConcreteSource(input){const sourceType=['internal','external'].includes(input?.sourceType)?input.sourceType:null;if(!sourceType)throw new Error('نوع منشأ بتن معتبر نیست');return createParty('concrete_sources',input,'source_type',sourceType);},
  listConcreteSources(){return db.prepare('SELECT id,code,name,source_type,archived FROM concrete_sources WHERE company_id=? ORDER BY archived,code,name').all(companyId);},
  createTestingLaboratory(input){const labType=['internal','external'].includes(input?.labType)?input.labType:null;if(!labType)throw new Error('نوع آزمایشگاه معتبر نیست');return createParty('testing_laboratories',input,'lab_type',labType);},
  listTestingLaboratories(){return db.prepare('SELECT id,code,name,lab_type,archived FROM testing_laboratories WHERE company_id=? ORDER BY archived,code,name').all(companyId);},
  registerExternalResult(input){const id=text(input?.id,'شناسه نتیجه خارجی');const sampleId=text(input?.sampleId,'نمونه');const labId=text(input?.testingLaboratoryId,'آزمایشگاه');const externalEventId=text(input?.externalEventId,'شناسه رویداد خارجی');const strength=optionalStrength(input?.strengthMpa);const testedAt=optionalUtc(input?.testedAt,'زمان آزمون');const receivedAt=optionalUtc(input?.receivedAt,'زمان دریافت')??clock();const notes=optionalText(input?.notes);const ownedSample=db.prepare(`SELECT s.id FROM samples s JOIN sampling_series ss ON ss.id=s.series_id WHERE s.id=? AND ss.company_id=?`).get(sampleId,companyId);if(!ownedSample)throw new Error('نمونه متعلق به این شرکت یافت نشد');const lab=db.prepare('SELECT id FROM testing_laboratories WHERE id=? AND company_id=? AND archived=0').get(labId,companyId);if(!lab)throw new Error('آزمایشگاه فعال متعلق به این شرکت یافت نشد');db.prepare(`INSERT INTO external_result_events(id,company_id,sample_id,testing_laboratory_id,external_event_id,strength_mpa,tested_at,received_at,received_by,notes) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,companyId,sampleId,labId,externalEventId,strength,testedAt,receivedAt,actor,notes);return{id,sampleId,externalEventId};},
  listExternalResults({limit=100}={}){const safe=Number.isSafeInteger(limit)&&limit>0&&limit<=200?limit:100;return db.prepare(`SELECT e.id,e.sample_id,e.testing_laboratory_id,l.name AS laboratory_name,e.external_event_id,e.strength_mpa,e.tested_at,e.received_at,e.received_by,e.notes FROM external_result_events e JOIN testing_laboratories l ON l.id=e.testing_laboratory_id AND l.company_id=e.company_id WHERE e.company_id=? ORDER BY e.received_at DESC,e.id DESC LIMIT ?`).all(companyId,safe);}
 };
}
