import {createAnalyticsService} from './analytics.js';

const requiredText=(value,label)=>{if(typeof value!=='string'||!value.trim())throw new Error(`${label} الزامی است`);return value.trim();};
const mean=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;
const eventStatus=eventType=>eventType==='resolved'?'resolved':eventType==='acknowledged'?'acknowledged':'open';

export function createReportingService(db,{companyId}){
 companyId=requiredText(companyId,'شرکت');
 const analytics=createAnalyticsService(db,{companyId});
 const specimenStatement=db.prepare(`SELECT s.id,s.age_days,s.due_at,r.strength_mpa,r.tested_at,r.tested_by,r.approved_by,r.state,sp.shape,sp.length_mm,sp.width_mm,sp.height_mm,sp.diameter_mm,sp.mass_kg,sp.volume_m3,sp.density_kg_m3 FROM samples s LEFT JOIN current_results r ON r.sample_id=s.id LEFT JOIN current_specimen_physical_measurements sp ON sp.sample_id=s.id WHERE s.series_id=? ORDER BY CASE WHEN s.age_days IS NULL THEN 9999 ELSE s.age_days END,s.id`);
 const buildSeries=(row,canonical=null)=>{const specimens=specimenStatement.all(row.id);const strength7=specimens.filter(x=>x.age_days===7&&x.state==='approved'&&typeof x.strength_mpa==='number').map(x=>x.strength_mpa);const strength28=specimens.filter(x=>x.age_days===28&&x.state==='approved'&&typeof x.strength_mpa==='number').map(x=>x.strength_mpa);return{id:row.id,sampledAt:row.sampled_at,samplerName:row.sampler_name,title:row.title??'',pourId:row.pour_id??null,pourOccurredAt:row.occurred_at??null,concreteSourceName:canonical?.sourceName??row.concrete_source_name??'',engineeringContext:canonical?{elementName:canonical.elementName,concreteClass:canonical.concreteClass,specifiedStrengthMpa:canonical.specifiedStrengthMpa,projectCharacteristicStrengthMpa:canonical.projectCharacteristicStrengthMpa,targetSlumpMm:canonical.targetSlumpMm,mixCode:canonical.mixCode,mixTitle:canonical.mixTitle,mixRevision:canonical.mixRevision,reference7Mpa:canonical.reference7Mpa,reference28Mpa:canonical.reference28Mpa,attainment7Percent:canonical.attainment7Percent,attainment28Percent:canonical.attainment28Percent}:null,freshConcrete:{slumpMm:canonical?.slumpMm??row.slump_mm??null,temperatureC:canonical?.temperatureC??row.concrete_temperature_c??null,measuredAt:canonical?.freshMeasuredAt??row.measured_at??null},specimens:specimens.map(x=>({id:x.id,ageDays:x.age_days,dueAt:x.due_at,state:x.state??null,strengthMpa:x.strength_mpa??null,testedAt:x.tested_at??null,testedBy:x.tested_by??null,approvedBy:x.approved_by??null,shape:x.shape??null,lengthMm:x.length_mm??null,widthMm:x.width_mm??null,heightMm:x.height_mm??null,diameterMm:x.diameter_mm??null,massKg:x.mass_kg??null,volumeM3:x.volume_m3??null,densityKgM3:x.density_kg_m3??null})),summary:{mean7Mpa:canonical?.mean7Mpa??mean(strength7),mean28Mpa:canonical?.mean28Mpa??mean(strength28),approved7Count:canonical?.strength7?.length??strength7.length,approved28Count:canonical?.strength28?.length??strength28.length}};};
 const organization=()=>{const company=db.prepare('SELECT id,name FROM companies WHERE id=?').get(companyId);const profile=db.prepare(`SELECT qc_manager_name,managing_director_name,company_name_en,registration_no,national_id,phone,email,website,address,laboratory_name,laboratory_code,report_footer,logo_relative_path,report_show_logo,report_show_company_name,report_show_qc_manager,report_show_contact FROM company_profiles WHERE company_id=?`).get(companyId)??{};return{company,profile:{qcManagerName:profile.qc_manager_name??'',managingDirectorName:profile.managing_director_name??'',companyNameEn:profile.company_name_en??'',registrationNo:profile.registration_no??'',nationalId:profile.national_id??'',phone:profile.phone??'',email:profile.email??'',website:profile.website??'',address:profile.address??'',laboratoryName:profile.laboratory_name??'',laboratoryCode:profile.laboratory_code??'',reportFooter:profile.report_footer??'',logoRelativePath:profile.logo_relative_path??'',reportShowLogo:(profile.report_show_logo??1)===1,reportShowCompanyName:(profile.report_show_company_name??1)===1,reportShowQcManager:(profile.report_show_qc_manager??1)===1,reportShowContact:(profile.report_show_contact??1)===1}};};
 const standardsFor=projectId=>{if(!projectId)return{profile:null,evaluationSummary:{total:0,pass:0,fail:0,notEvaluated:0},acceptanceEvaluated:false};const assignment=db.prepare(`SELECT a.profile_id,p.code,p.title,p.authority,p.document_code,p.document_version,p.effective_date FROM project_rule_profile_assignments a JOIN rule_profiles p ON p.id=a.profile_id AND p.company_id=a.company_id WHERE a.company_id=? AND a.project_id=?`).get(companyId,projectId);if(!assignment)return{profile:null,evaluationSummary:{total:0,pass:0,fail:0,notEvaluated:0},acceptanceEvaluated:false};const counts=db.prepare(`SELECT COUNT(*) AS total,SUM(CASE WHEN overall_status='pass' THEN 1 ELSE 0 END) AS pass,SUM(CASE WHEN overall_status='fail' THEN 1 ELSE 0 END) AS fail,SUM(CASE WHEN overall_status='not_evaluated' THEN 1 ELSE 0 END) AS not_evaluated FROM result_rule_evaluations WHERE company_id=? AND project_id=? AND profile_id=?`).get(companyId,projectId,assignment.profile_id);const summary={total:Number(counts.total??0),pass:Number(counts.pass??0),fail:Number(counts.fail??0),notEvaluated:Number(counts.not_evaluated??0)};return{profile:{id:assignment.profile_id,code:assignment.code,title:assignment.title,authority:assignment.authority,documentCode:assignment.document_code,documentVersion:assignment.document_version,effectiveDate:assignment.effective_date??null},evaluationSummary:summary,acceptanceEvaluated:summary.total>0};};
 const currentExceptions=(projectId=null,seriesId=null)=>{const clauses=['e.company_id=?',"e.event_type!='resolved'"],params=[companyId];if(projectId){clauses.push('e.project_id=?');params.push(projectId);}if(seriesId){clauses.push('e.series_id=?');params.push(seriesId);}return db.prepare(`SELECT e.exception_key,e.event_type,e.category,e.severity,e.project_id,e.series_id,e.sample_id,e.title,e.detail,e.source_type,e.source_ref,e.observed_at,e.actor,e.created_at FROM current_qc_exceptions e WHERE ${clauses.join(' AND ')} ORDER BY CASE e.severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,e.observed_at DESC`).all(...params).map(row=>({exceptionKey:row.exception_key,status:eventStatus(row.event_type),category:row.category,severity:row.severity,projectId:row.project_id??null,seriesId:row.series_id??null,sampleId:row.sample_id??null,title:row.title,detail:row.detail,sourceType:row.source_type,sourceRef:row.source_ref??null,observedAt:row.observed_at,actor:row.actor,createdAt:row.created_at}));};
 return{
  samplingSeriesReport(seriesId){seriesId=requiredText(seriesId,'نوبت نمونه‌برداری');const row=db.prepare(`SELECT ss.id,ss.project_id,ss.sampled_at,ss.sampler_name,ss.title,ss.pour_id,p.occurred_at,pr.name AS project_name,pr.customer_name,pr.address,COALESCE(cs.name,'') AS concrete_source_name,fc.slump_mm,fc.concrete_temperature_c,fc.measured_at FROM sampling_series ss LEFT JOIN projects pr ON pr.id=ss.project_id LEFT JOIN pours p ON p.id=ss.pour_id LEFT JOIN pour_qc_contexts pc ON pc.pour_id=ss.pour_id LEFT JOIN concrete_sources cs ON cs.id=pc.concrete_source_id LEFT JOIN current_fresh_concrete_measurements fc ON fc.series_id=ss.id WHERE ss.id=? AND ss.company_id=?`).get(seriesId,companyId);if(!row)throw new Error('نوبت نمونه‌برداری یافت نشد');const canonical=analytics.seriesDataset(row.project_id?{projectId:row.project_id}:{}).find(item=>item.seriesId===seriesId)??null;const {company,profile}=organization();return{schema:'tolou-qc-series-report',schemaVersion:3,generatedAt:new Date().toISOString(),company:{id:company.id,name:company.name},organization:profile,project:row.project_id?{id:row.project_id,name:row.project_name,customerName:row.customer_name,address:row.address}:null,qcDataset:canonical,series:buildSeries(row,canonical),standards:standardsFor(row.project_id),actionItems:currentExceptions(row.project_id??null,seriesId),notes:['مرجع عملیاتی ۷ و ۲۸ روزه با پذیرش استانداردی یکسان نیست. نتیجه استانداردی فقط در صورت وجود Rule Profile و Evaluation ثبت‌شده قابل استناد است.']};},
  projectQc(input={}){
   const projectId=requiredText(input.projectId,'پروژه');
   const project=db.prepare('SELECT id,name,customer_name,address FROM projects WHERE id=? AND company_id=?').get(projectId,companyId);
   if(!project)throw new Error('پروژه یافت نشد');
   const {company,profile}=organization();
   const summary=analytics.summary({projectId,startAt:input.startAt??null,endAt:input.endAt??null});
   const {startAt,endAt}=summary.filters;
   const clauses=['ss.company_id=?','ss.project_id=?'],params=[companyId,projectId];
   if(startAt){clauses.push('ss.sampled_at>=?');params.push(startAt);}
   if(endAt){clauses.push('ss.sampled_at<=?');params.push(endAt);}
   const seriesRows=db.prepare(`SELECT ss.id,ss.sampled_at,ss.sampler_name,ss.title,ss.pour_id,p.occurred_at,COALESCE(cs.name,'') AS concrete_source_name,fc.slump_mm,fc.concrete_temperature_c,fc.measured_at FROM sampling_series ss LEFT JOIN pours p ON p.id=ss.pour_id LEFT JOIN pour_qc_contexts pc ON pc.pour_id=ss.pour_id LEFT JOIN concrete_sources cs ON cs.id=pc.concrete_source_id LEFT JOIN current_fresh_concrete_measurements fc ON fc.series_id=ss.id WHERE ${clauses.join(' AND ')} ORDER BY ss.sampled_at`).all(...params);
   const canonicalById=new Map(summary.seriesDataset.map(row=>[row.seriesId,row]));
   const series=seriesRows.map(row=>buildSeries(row,canonicalById.get(row.id)??null));
   return{schema:'tolou-qc-project-report',schemaVersion:4,generatedAt:new Date().toISOString(),company:{id:company.id,name:company.name},organization:profile,project:{id:project.id,name:project.name,customerName:project.customer_name,address:project.address},filters:summary.filters,counts:{samplingSeries:summary.seriesDataset.length,approvedStrengthResults:summary.strength.statistics.count},qcDataset:summary.seriesDataset,series,analytics:summary,standards:standardsFor(projectId),actionItems:currentExceptions(projectId,null),notes:['گزارش پروژه از Canonical QC Dataset تغذیه می‌شود. وضعیت مرجع عملیاتی و ارزیابی Rule Profile دو مفهوم مستقل‌اند و در این گزارش با هم ادغام نمی‌شوند.']};
  }
 };
}
