import {useCallback,useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import type {AnalyticsMetric,AnalyticsSummary,ProjectSummary,StrengthAnalyticsMetric} from '../shared/ipc';
import {PersianDateTimeInput} from './PersianDateTimeInput';
import './analytics-workbench.css';

function number(value:number|null,digits=2){return value===null?'—':value.toLocaleString('fa-IR',{maximumFractionDigits:digits});}
function Sparkline({metric}:{metric:AnalyticsMetric}){const points=metric.trend;if(points.length<2)return <div className="analytics-empty">برای نمودار حداقل دو مشاهده لازم است.</div>;const values=points.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),span=max-min||1;const coords=points.map((p,i)=>`${(i/(points.length-1))*100},${36-((p.value-min)/span)*32}`).join(' ');return <svg className="analytics-spark" viewBox="0 0 100 40" role="img" aria-label={`روند ${metric.name}`}><polyline points={coords} fill="none" vectorEffect="non-scaling-stroke"/></svg>}
function MetricCard({title,metric}:{title:string;metric:AnalyticsMetric}){const s=metric.statistics;return <article className="analytics-card glass"><div className="analytics-card-head"><div><p className="eyebrow">{metric.unit}</p><h4>{title}</h4></div><strong>{number(s.mean)}</strong></div><div className="analytics-stats"><span>تعداد<b>{s.count.toLocaleString('fa-IR')}</b></span><span>حداقل<b>{number(s.min)}</b></span><span>حداکثر<b>{number(s.max)}</b></span><span>SD<b>{number(s.sampleSd)}</b></span><span>CV<b>{s.cvPercent===null?'—':`${number(s.cvPercent)}٪`}</b></span></div><Sparkline metric={metric}/></article>}
function StrengthAges({metric}:{metric:StrengthAnalyticsMetric}){const rows=Object.entries(metric.byAge);if(!rows.length)return null;return <div className="analytics-age"><strong>تفکیک مقاومت بر حسب سن نمونه</strong>{rows.map(([age,s])=><span key={age}>{age==='witness'?'شاهد':`${Number(age).toLocaleString('fa-IR')} روزه`} · n={s.count.toLocaleString('fa-IR')} · میانگین {number(s.mean)} MPa</span>)}</div>}
export function AnalyticsWorkbench({refreshKey=0}:{refreshKey?:number}){
 const [projects,setProjects]=useState<ProjectSummary[]>([]),[data,setData]=useState<AnalyticsSummary|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async(input={})=>{setBusy(true);try{const r=await window.tolou.analyticsSummary(input);if(!r.ok)throw new Error(r.message);setData(r.data);}catch(e){setMessage(e instanceof Error?e.message:'تحلیل داده‌ها انجام نشد');}finally{setBusy(false);}},[]);
 useEffect(()=>{void Promise.all([window.tolou.listProjects(),window.tolou.analyticsSummary({})]).then(([p,a])=>{if(!p.ok)throw new Error(p.message);if(!a.ok)throw new Error(a.message);setProjects(p.data.filter(x=>x.archived===0));setData(a.data);}).catch(e=>setMessage(e instanceof Error?e.message:'بارگذاری تحلیل QC انجام نشد'));},[refreshKey]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setMessage('');await load({projectId:String(f.get('projectId')??'')||null,startAt:String(f.get('startAt')??'')||null,endAt:String(f.get('endAt')??'')||null});}
 return <section className="analytics-workbench glass"><div className="panel-heading"><div><p className="eyebrow">QC Analytics Core</p><h3>تحلیل آماری کنترل کیفیت</h3></div><span className="count-badge">Standards-neutral</span></div><form className="analytics-filter" onSubmit={submit}><label>پروژه<select name="projectId" defaultValue=""><option value="">همه پروژه‌ها</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>از تاریخ<PersianDateTimeInput name="startAt"/></label><label>تا تاریخ<PersianDateTimeInput name="endAt"/></label><button className="primary-button" disabled={busy}>{busy?'در حال تحلیل…':'اعمال فیلتر'}</button></form>{message&&<div className="workbench-message" role="status">{message}</div>}{data&&<><div className="analytics-grid"><MetricCard title="مقاومت فشاری" metric={data.strength}/><MetricCard title="اسلامپ" metric={data.slump}/><MetricCard title="دمای بتن" metric={data.concreteTemperature}/><MetricCard title="جرم حجمی بتن سخت‌شده" metric={data.hardenedDensity}/></div><StrengthAges metric={data.strength}/><p className="analytics-note">مقاومت فقط از نتایج تأییدشده محاسبه می‌شود. آمار این بخش صرفاً توصیفی است و هیچ معیار پذیرش استانداردی اعمال نمی‌کند.</p></>}</section>;
}
