import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import './entertainment-workspace.css';

type GameRecord={id:string;player:string;score:number;delivered:number;accuracy:number;bestStreak:number;seconds:number;createdAt:string};
type Material={name:string;short:string;unit:string};
type Order={id:number;name:string;customer:string;volume:number;targets:number[];remaining:number;patience:number;reward:number;color:string};
type Mixer={order:Order;quality:number;remaining:number;state:'mixing'|'ready'}|null;
type RunState={score:number;reputation:number;streak:number;bestStreak:number;delivered:number;qualitySum:number;seconds:number;orders:Order[];nextOrderId:number;spawnIn:number;selectedOrderId:number|null;hopper:number[];mixer:Mixer};
type OverlayMode='playing'|'paused'|'exit-confirm';

const RECORD_KEY='tolou-production-management:records';
const PLAYER_KEY='tolou-production-management:last-player';
const MATERIALS:Material[]=[{name:'سیمان',short:'1',unit:'kg'},{name:'آب',short:'2',unit:'kg'},{name:'ماسه',short:'3',unit:'kg'},{name:'شن',short:'4',unit:'kg'},{name:'افزودنی',short:'5',unit:'kg'},{name:'الیاف / ماده ویژه',short:'6',unit:'kg'}];
const RECIPES=[
 {name:'بتن معمولی C25',base:[340,175,780,1030,3.4,0],reward:330,color:'#6dc7d5'},
 {name:'بتن سازه‌ای C30',base:[380,180,760,1010,4.2,0],reward:390,color:'#ffb75d'},
 {name:'بتن پمپی C35',base:[410,180,820,930,5.5,0],reward:470,color:'#8bd2a6'},
 {name:'بتن الیافی',base:[400,178,790,960,5.2,7],reward:560,color:'#c39be6'},
 {name:'بتن ویژه روان',base:[430,165,810,900,7.2,0],reward:650,color:'#7fb5ff'},
];
const CUSTOMERS=['پروژه برج آفتاب','سازه یزد مرکزی','مجتمع صنعتی طلوع','پروژه سپهر','کارگاه توسعه شرق','پروژه مسکونی نیلگون'];
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
const fa=(v:number,digits=0)=>v.toLocaleString('fa-IR',{maximumFractionDigits:digits,minimumFractionDigits:digits});
const timeLabel=(seconds:number)=>`${Math.floor(seconds/60).toLocaleString('fa-IR').padStart(2,'۰')}:${Math.floor(seconds%60).toLocaleString('fa-IR').padStart(2,'۰')}`;
const emptyHopper=()=>MATERIALS.map(()=>0);
function readRecords():GameRecord[]{try{const parsed=JSON.parse(localStorage.getItem(RECORD_KEY)||'[]');return Array.isArray(parsed)?parsed.filter(x=>x&&typeof x.player==='string'&&Number.isFinite(x.score)).sort((a,b)=>b.score-a.score).slice(0,10):[];}catch{return[];}}
function createOrder(id:number,pressure:number):Order{const maxRecipe=pressure>0.72?5:pressure>0.48?4:pressure>0.22?3:2;const recipe=RECIPES[Math.floor(Math.random()*maxRecipe)];const volume=[5,6,7,8,9,10][Math.floor(Math.random()*6)];const factor=.88+Math.random()*.24;const targets=recipe.base.map((v,index)=>index<5?Math.round(v*factor*10)/10:v);const patience=Math.round(clamp(78-pressure*30+Math.random()*24,42,92));return{id,name:recipe.name,customer:CUSTOMERS[Math.floor(Math.random()*CUSTOMERS.length)],volume,targets,remaining:patience,patience,reward:recipe.reward+volume*18,color:recipe.color};}
function newRun():RunState{const first=createOrder(1,0);return{score:0,reputation:100,streak:0,bestStreak:0,delivered:0,qualitySum:0,seconds:0,orders:[first],nextOrderId:2,spawnIn:9,selectedOrderId:first.id,hopper:emptyHopper(),mixer:null};}
function qualityFor(values:number[],targets:number[]){const relevant=targets.map((t,i)=>({t,v:values[i]})).filter(x=>x.t>0);if(!relevant.length)return 0;const meanError=relevant.reduce((sum,x)=>sum+Math.abs(x.v-x.t)/x.t,0)/relevant.length;return Math.round(clamp(100-meanError*140,0,100));}

export function EntertainmentWorkspace(){
 const[records,setRecords]=useState<GameRecord[]>(()=>readRecords());
 const[player,setPlayer]=useState(()=>localStorage.getItem(PLAYER_KEY)||'');
 const[gameOpen,setGameOpen]=useState(false);
 const[mode,setMode]=useState<OverlayMode>('playing');
 const[run,setRun]=useState<RunState>(()=>newRun());
 const[notice,setNotice]=useState('');
 const overlayRef=useRef<HTMLDivElement|null>(null);
 const holdRef=useRef<number|null>(null);
 const runRef=useRef(run);useEffect(()=>{runRef.current=run},[run]);
 const selected=useMemo(()=>run.orders.find(o=>o.id===run.selectedOrderId)??null,[run.orders,run.selectedOrderId]);
 const hopperQuality=selected?qualityFor(run.hopper,selected.targets):0;
 const best=records[0]?.score??0;
 const avgAccuracy=run.delivered?run.qualitySum/run.delivered:0;
 const pressure=clamp(run.seconds/420+run.score/18000,0,1);

 const saveRecord=useCallback(()=>{const state=runRef.current;const clean=player.trim().slice(0,24)||'بازیکن بدون نام';const row:GameRecord={id:`GAME-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,player:clean,score:Math.round(state.score),delivered:state.delivered,accuracy:state.delivered?Math.round(state.qualitySum/state.delivered):0,bestStreak:state.bestStreak,seconds:Math.round(state.seconds),createdAt:new Date().toISOString()};const next=[...readRecords(),row].sort((a,b)=>b.score-a.score).slice(0,10);localStorage.setItem(RECORD_KEY,JSON.stringify(next));localStorage.setItem(PLAYER_KEY,clean);setRecords(next);return row;},[player]);
 const closeFullscreen=useCallback(async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}},[]);
 const exitGame=useCallback(async(save:boolean)=>{if(save)saveRecord();if(holdRef.current!==null){window.clearInterval(holdRef.current);holdRef.current=null;}await closeFullscreen();setGameOpen(false);setMode('playing');setNotice('');},[closeFullscreen,saveRecord]);
 const launch=useCallback(async()=>{if(!player.trim()){setNotice('برای اجرای بازی، نام بازیکن را وارد کنید.');return;}localStorage.setItem(PLAYER_KEY,player.trim().slice(0,24));setRun(newRun());setMode('playing');setNotice('');setGameOpen(true);requestAnimationFrame(async()=>{try{await overlayRef.current?.requestFullscreen?.();}catch{}});},[player]);

 useEffect(()=>{if(!gameOpen||mode!=='playing')return;const timer=window.setInterval(()=>setRun(prev=>{
   let orders=prev.orders.map(o=>({...o,remaining:o.remaining-.25}));let reputation=prev.reputation;const expired=orders.filter(o=>o.remaining<=0);if(expired.length){reputation=clamp(reputation-expired.length*20,0,100);orders=orders.filter(o=>o.remaining>0);}
   let spawnIn=prev.spawnIn-.25;let nextOrderId=prev.nextOrderId;if(spawnIn<=0&&orders.length<4){orders=[...orders,createOrder(nextOrderId,clamp(prev.seconds/420+prev.score/18000,0,1))];nextOrderId+=1;spawnIn=clamp(13-(prev.seconds/120),6,13)+Math.random()*5;}else if(spawnIn<=0)spawnIn=2;
   let mixer=prev.mixer;if(mixer?.state==='mixing'){const remaining=mixer.remaining-.25;mixer=remaining<=0?{...mixer,remaining:0,state:'ready'}:{...mixer,remaining};}
   const selectedStill=orders.some(o=>o.id===prev.selectedOrderId);const selectedOrderId=selectedStill?prev.selectedOrderId:(orders[0]?.id??null);const hopper=selectedOrderId===prev.selectedOrderId?prev.hopper:emptyHopper();
   return{...prev,seconds:prev.seconds+.25,orders,reputation,spawnIn,nextOrderId,mixer,selectedOrderId,hopper};
 }),250);return()=>window.clearInterval(timer);},[gameOpen,mode]);
 useEffect(()=>{if(gameOpen&&run.reputation<=0&&mode==='playing'){setMode('exit-confirm');setNotice('اعتبار شرکت به صفر رسید؛ شیفت پایان یافته است.');}},[gameOpen,run.reputation,mode]);
 useEffect(()=>{if(!gameOpen)return;const key=(event:KeyboardEvent)=>{if(mode!=='playing')return;if(event.code==='Escape'){event.preventDefault();setMode('paused');return;}const match=event.code.match(/^(?:Digit|Numpad)([1-6])$/);if(match){event.preventDefault();dose(Number(match[1])-1,event.shiftKey?.8:4.5);}else if(event.code==='Space'){event.preventDefault();startMix();}else if(event.code==='Enter'){event.preventDefault();deliver();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 useEffect(()=>()=>{if(holdRef.current!==null)window.clearInterval(holdRef.current)},[]);

 function selectOrder(id:number){if(mode!=='playing')return;setRun(prev=>prev.selectedOrderId===id?prev:{...prev,selectedOrderId:id,hopper:emptyHopper()});}
 function dose(index:number,amount=5){if(mode!=='playing'||!selected||selected.targets[index]<=0)return;setRun(prev=>({...prev,hopper:prev.hopper.map((v,i)=>i===index?Math.round((v+amount)*10)/10:v)}));}
 function startHold(index:number){dose(index,2);if(holdRef.current!==null)window.clearInterval(holdRef.current);holdRef.current=window.setInterval(()=>dose(index,.9),55);}
 function stopHold(){if(holdRef.current!==null){window.clearInterval(holdRef.current);holdRef.current=null;}}
 function discardHopper(){setRun(prev=>({...prev,hopper:emptyHopper()}));setNotice('هاپر تخلیه شد.');}
 function startMix(){const current=runRef.current;if(mode!=='playing'||current.mixer||!selected)return;const quality=qualityFor(current.hopper,selected.targets);if(current.hopper.every(v=>v===0)){setNotice('ابتدا مواد سفارش را توزین کنید.');return;}setRun(prev=>({...prev,mixer:{order:selected,quality,remaining:6,state:'mixing'},orders:prev.orders.filter(o=>o.id!==selected.id),selectedOrderId:prev.orders.find(o=>o.id!==selected.id)?.id??null,hopper:emptyHopper()}));setNotice(`اختلاط سفارش ${selected.id.toLocaleString('fa-IR')} آغاز شد.`);}
 function deliver(){const current=runRef.current;if(mode!=='playing'||current.mixer?.state!=='ready')return;const mixer=current.mixer;const quality=mixer.quality;const speed=Math.max(0,Math.round(mixer.order.remaining*2));const good=quality>=90;const streak=good?current.streak+1:0;const combo=Math.min(2,1+streak*.1);const points=Math.round((mixer.order.reward+quality*2+speed)*combo);setRun(prev=>({...prev,score:prev.score+points,delivered:prev.delivered+1,qualitySum:prev.qualitySum+quality,streak,bestStreak:Math.max(prev.bestStreak,streak),reputation:clamp(prev.reputation+(good&&((prev.delivered+1)%5===0)?5:0),0,100),mixer:null}));setNotice(`تحویل انجام شد · دقت ${fa(quality)}٪ · +${fa(points)} امتیاز`);}
 function discardMixer(){if(!run.mixer)return;setRun(prev=>({...prev,score:Math.max(0,prev.score-75),mixer:null,streak:0}));setNotice('بتن داخل میکسر تخلیه شد · ۷۵ امتیاز کسر شد.');}

 return <>
  <section className="workspace-intro entertainment-intro"><p className="eyebrow eyebrow--accent">سرگرمی</p><h2>بازی‌های طلوع</h2><p>فضای بازی از اطلاعات مهندسی و QC جداست و هیچ رکوردی روی داده‌های پروژه‌ها اثر نمی‌گذارد.</p></section>
  <section className="entertainment-shell panel--wide">
   <aside className="entertainment-leaderboard glass"><div className="panel-heading"><div><p className="eyebrow">رکوردها</p><h3>برترین بازیکنان</h3></div><span className="count-badge">{records.length.toLocaleString('fa-IR')}</span></div>{records.length===0?<div className="entertainment-empty">هنوز رکوردی ثبت نشده است.</div>:<div className="entertainment-records">{records.map((r,i)=><article key={r.id} className={i===0?'is-first':''}><span>{(i+1).toLocaleString('fa-IR')}</span><div><strong>{r.player}</strong><small>{r.delivered.toLocaleString('fa-IR')} تحویل · دقت {r.accuracy.toLocaleString('fa-IR')}٪</small></div><b>{r.score.toLocaleString('fa-IR')}</b></article>)}</div>}</aside>
   <div className="entertainment-library glass"><div className="game-library-card is-selected"><div className="game-library-icon">TP</div><div className="game-library-copy"><p className="eyebrow eyebrow--accent">TOLOU ARCADE</p><h3>طلوع مدیریت تولید</h3><p>در نقش مسئول بچینگ، سفارش بگیر، مواد را توزین کن، اختلاط را مدیریت کن و بتن را به‌موقع تحویل بده. منطق بازی بر پایه همان بازی آرکید ارائه‌شده برای طلوع تنظیم شده است.</p><div className="game-library-meta"><span>بازی بی‌پایان</span><span>ثبت ۱۰ رکورد برتر</span><span>کنترل ماوس و کیبورد</span><span>اجرای تمام‌صفحه</span></div></div></div><div className="game-launch-panel"><label>نام بازیکن<input value={player} maxLength={24} onChange={e=>setPlayer(e.target.value)} placeholder="نام مسئول بچینگ"/></label><div className="game-best"><small>بهترین رکورد این دستگاه</small><strong>{best.toLocaleString('fa-IR')}</strong></div>{notice&&!gameOpen&&<div className="game-notice">{notice}</div>}<button type="button" className="primary-button game-launch-button" onClick={()=>void launch()}>اجرای بازی</button></div></div>
  </section>
  {gameOpen&&<div ref={overlayRef} className="tolou-game-overlay" dir="rtl">
    <header className="game-hostbar"><div><strong>طلوع مدیریت تولید</strong><span>{player.trim()}</span></div><div className="game-hostbar-metrics"><span>امتیاز <b>{fa(run.score)}</b></span><span>رکورد <b>{fa(Math.max(best,run.score))}</b></span><span>زمان <b>{timeLabel(run.seconds)}</b></span></div><div className="game-host-actions"><button type="button" onClick={()=>setMode(mode==='paused'?'playing':'paused')}>{mode==='paused'?'ادامه':'توقف'}</button><button type="button" className="danger" onClick={()=>setMode('exit-confirm')}>خروج</button></div></header>
    <main className="production-game"><aside className="production-orders"><div className="production-section-head"><div><small>ORDER QUEUE</small><h2>صف سفارش‌ها</h2></div><span>{run.orders.length.toLocaleString('fa-IR')} / ۴</span></div><div className="production-order-list">{run.orders.length===0?<div className="production-empty">منتظر سفارش بعدی…</div>:run.orders.map(order=><button type="button" key={order.id} className={`production-order ${run.selectedOrderId===order.id?'is-selected':''} ${order.remaining<18?'is-urgent':''}`} style={{'--order-color':order.color} as React.CSSProperties} onClick={()=>selectOrder(order.id)}><div><span>کامیون {order.id.toLocaleString('fa-IR')}</span><em>{order.name}</em></div><strong>{order.customer}</strong><small>{order.volume.toLocaleString('fa-IR')} m³ · {timeLabel(Math.max(0,order.remaining))}</small><i style={{width:`${clamp(order.remaining/order.patience*100,0,100)}%`}}/></button>)}</div><div className="production-reputation"><div><span>اعتبار شرکت</span><strong>{fa(run.reputation)}٪</strong></div><i><b style={{width:`${run.reputation}%`}}/></i></div><div className="production-player"><small>مسئول شیفت</small><strong>{player.trim()}</strong><span>تحویل موفق: {run.delivered.toLocaleString('fa-IR')}</span></div></aside>
     <section className="production-main"><div className="production-stage"><div className="production-factory-art"><div className="silo silo-a"/><div className="silo silo-b"/><div className="silo silo-c"/><div className="batch-tower"><span>TOLOU</span></div><div className={`mixer-truck ${run.mixer?.state==='ready'?'is-ready':''}`}><div className="truck-drum"/><div className="truck-cab"/><i/><i/></div></div><div className="production-stage-copy"><p>{run.mixer?.state==='mixing'?'میکسر در حال کار است':run.mixer?.state==='ready'?'بتن آماده تحویل است':selected?'سفارش انتخاب شده؛ توزین را انجام بده':'یک سفارش انتخاب کن'}</p><strong>{run.mixer?.state==='mixing'?`${Math.ceil(run.mixer.remaining).toLocaleString('fa-IR')} ثانیه تا آماده‌شدن`:run.mixer?.state==='ready'?`دقت بچ ${run.mixer.quality.toLocaleString('fa-IR')}٪`:`فشار کاری ${Math.ceil(1+pressure*3).toLocaleString('fa-IR')}`}</strong></div></div>
      <section className="production-console"><div className="production-console-head"><div><small>WEIGHING HOPPER</small><h2>{selected?`${selected.name} · کامیون ${selected.id.toLocaleString('fa-IR')}`:'هاپر توزین'}</h2></div><div className="production-accuracy"><small>دقت فعلی</small><strong>{selected&&run.hopper.some(v=>v>0)?`${fa(hopperQuality)}٪`:'—'}</strong></div></div><div className="production-materials">{MATERIALS.map((m,index)=>{const target=selected?.targets[index]??0;const value=run.hopper[index];const ratio=target?clamp(value/(target*1.25)*100,0,100):0;const exact=target>0&&Math.abs(value-target)<=Math.max(1,target*.025);return <button type="button" key={m.name} disabled={mode!=='playing'||!selected||target<=0} className={`production-material ${exact?'is-exact':''}`} onPointerDown={()=>startHold(index)} onPointerUp={stopHold} onPointerCancel={stopHold} onPointerLeave={stopHold}><div><span>{m.name}</span><kbd>{m.short}</kbd></div><strong>{fa(value,1)} <small>/ {target?fa(target,1):'—'} {m.unit}</small></strong><i><b style={{width:`${ratio}%`}}/></i><em>{target<=0?'نیاز نیست':exact?'مقدار دقیق':value>target?'بیش از هدف':'نگه دار برای توزین'}</em></button>})}</div><div className="production-console-actions"><button type="button" className="secondary-button" disabled={!selected||mode!=='playing'} onClick={discardHopper}>تخلیه هاپر</button><button type="button" className="primary-button" disabled={!selected||!!run.mixer||mode!=='playing'} onClick={startMix}>شروع اختلاط <span>Space</span></button></div></section>
      <section className={`production-mixer ${run.mixer?.state??''}`}><div className="production-mixer-wheel">↻</div><div><small>MIXER</small><strong>{!run.mixer?'میکسر آماده‌به‌کار':run.mixer.state==='mixing'?`اختلاط ${run.mixer.order.name}`:`بتن آماده · کامیون ${run.mixer.order.id.toLocaleString('fa-IR')}`}</strong><span>{!run.mixer?'پس از توزین، اختلاط را شروع کنید.':run.mixer.state==='mixing'?`دقت بچ ${fa(run.mixer.quality)}٪`:`برای ثبت تحویل، دکمه تحویل را بزنید.`}</span></div><div className="production-mixer-actions">{run.mixer&&<button type="button" className="secondary-button" onClick={discardMixer}>تخلیه</button>}<button type="button" className="primary-button" disabled={run.mixer?.state!=='ready'||mode!=='playing'} onClick={deliver}>تحویل بتن <span>Enter</span></button></div></section>
     </section></main>
    <footer className="production-footer"><span>۱–۶ توزین · Space اختلاط · Enter تحویل · Esc توقف</span><span>زنجیره {fa(Math.min(2,1+run.streak*.1),1)}× · بهترین زنجیره {run.bestStreak.toLocaleString('fa-IR')}</span></footer>
    {notice&&<div className="production-toast">{notice}</div>}
    {mode==='paused'&&<div className="game-modal-backdrop"><div className="game-modal"><p className="eyebrow eyebrow--accent">PAUSED</p><h2>بازی متوقف شد</h2><p>زمان سفارش‌ها متوقف است.</p><div><button className="primary-button" onClick={()=>setMode('playing')}>ادامه بازی</button><button className="secondary-button" onClick={()=>setMode('exit-confirm')}>پایان شیفت</button></div></div></div>}
    {mode==='exit-confirm'&&<div className="game-modal-backdrop"><div className="game-modal game-modal--exit"><p className="eyebrow eyebrow--accent">END SHIFT</p><h2>پایان بازی</h2><p>امتیاز فعلی <strong>{run.score.toLocaleString('fa-IR')}</strong> است. نتیجه را ثبت کنیم؟</p><div className="game-result-preview"><span>تحویل {run.delivered.toLocaleString('fa-IR')}</span><span>دقت میانگین {fa(avgAccuracy)}٪</span><span>زنجیره {run.bestStreak.toLocaleString('fa-IR')}</span><span>{timeLabel(run.seconds)}</span></div><div><button className="primary-button" onClick={()=>void exitGame(true)}>ثبت رکورد و خروج</button><button className="secondary-button" onClick={()=>void exitGame(false)}>خروج بدون ثبت</button><button className="text-button" onClick={()=>setMode('playing')} disabled={run.reputation<=0}>بازگشت به بازی</button></div></div></div>}
   </div>}
 </>;
}
