import { useEffect, useState } from 'react';
import type { ExternalResultSummary, FreshConcreteSummary, PourContextSummary, PourSpecification, ResultRevision, SpecimenPhysicsSummary } from '../shared/ipc';
import { isoToPersianLocal } from './jalali';
import { RuleProfileEvaluationPanel } from './RuleProfileEvaluationPanel';
import './management-sample-drawer.css';

export type ManagementSampleRow={sampleId:string;seriesId:string;projectId:string|null;projectName:string|null;pourId:string|null;sampledAt:string;samplerName:string;ageDays:number|null;dueAt:string|null;resultState:string|null;strengthMpa:number|null;testedAt:string|null;testedBy:string|null;approvedBy:string|null;referenceMpa:number|null;attainmentPercent:number|null;operationalStatus:'met_reference'|'below_reference'|'unclassified'|'not_evaluated';cementKgM3:number|null;mixCode:string|null;mixRevision:number|null;concreteSourceName:string|null;elementName:string|null;concreteClass:string|null};
type Props={row:ManagementSampleRow;onClose:()=>void};
const value=(text:string|null|undefined)=>text?.trim()||'—';
const mpa=(n:number|null|undefined)=>n==null?'—':`${n.toLocaleString('fa-IR',{maximumFractionDigits:2})} MPa`;
const pct=(n:number|null)=>n==null?'—':`${n.toLocaleString('fa-IR',{maximumFractionDigits:1})}٪`;
const stateLabel=(state:string|null)=>state==='approved'?'تأییدشده':state==='draft'?'پیش‌نویس':state==='void'?'باطل':state||'بدون نتیجه';

export function ManagementSampleDrawer({row,onClose}:Props){
 const[spec,setSpec]=useState<PourSpecification|null>(null);const[context,setContext]=useState<PourContextSummary|null>(null);const[physics,setPhysics]=useState<SpecimenPhysicsSummary|null>(null);const[fresh,setFresh]=useState<FreshConcreteSummary|null>(null);const[history,setHistory]=useState<ResultRevision[]>([]);const[external,setExternal]=useState<ExternalResultSummary[]>([]);const[attachmentCounts,setAttachmentCounts]=useState<Record<string,number>>({});const[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;setMessage('');void(async()=>{try{const[ph,fr,hi,ex]=await Promise.all([window.tolou.getSpecimenPhysics(row.sampleId),window.tolou.getFreshConcrete(row.seriesId),window.tolou.resultHistory(row.sampleId),window.tolou.listExternalResults(2000)]);if(!ph.ok)throw new Error(ph.message);if(!fr.ok)throw new Error(fr.message);if(!hi.ok)throw new Error(hi.message);if(!ex.ok)throw new Error(ex.message);if(!alive)return;setPhysics(ph.data);setFresh(fr.data);setHistory([...hi.data].sort((a,b)=>b.revision-a.revision));const related=ex.data.filter(item=>item.sample_id===row.sampleId);setExternal(related);const counts:Record<string,number>={};await Promise.all(related.map(async item=>{const result=await window.tolou.listExternalAttachments(item.external_event_id);if(result.ok)counts[item.external_event_id]=result.data.length;}));if(alive)setAttachmentCounts(counts);if(row.pourId){const[s,c]=await Promise.all([window.tolou.getPourSpecification(row.pourId),window.tolou.getPourContext(row.pourId)]);if(!s.ok)throw new Error(s.message);if(!c.ok)throw new Error(c.message);if(alive){setSpec(s.data);setContext(c.data);}}}catch(error){if(alive)setMessage(error instanceof Error?error.message:'بخشی از پرونده نمونه بارگذاری نشد.');}})();return()=>{alive=false;};},[row.sampleId,row.seriesId,row.pourId]);
 const status=row.operationalStatus==='met_reference'?'قبول مدیریتی':row.operationalStatus==='below_reference'?'رد مدیریتی':'بدون ارزیابی';
 const currentApprovedRevision=row.resultState==='approved'?(history[0]?.revision??null):null;
 return <div className="management-drawer-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><aside className="management-sample-drawer glass" role="dialog" aria-modal="true" aria-label="پرونده نمونه"><header><div><p className="eyebrow eyebrow--accent">SAMPLE TRACEABILITY</p><h3>پرونده نمونه</h3><small>{row.sampleId}</small></div><button type="button" className="management-drawer-close" onClick={onClose}>×</button></header>{message&&<div className="workbench-message">{message}</div>}<div className="management-drawer-status"><span className={row.operationalStatus==='below_reference'?'is-danger':'is-ok'}>{status}</span><strong>{mpa(row.strengthMpa)}</strong><small>دستیابی {pct(row.attainmentPercent)} از مرجع {mpa(row.referenceMpa)}</small></div>
 <section><h4>ردیابی عملیات</h4><div className="management-drawer-grid"><div><small>پروژه</small><strong>{value(row.projectName)}</strong></div><div><small>عضو / محل بتن‌ریزی</small><strong>{value(row.elementName||spec?.element_name)}</strong></div><div><small>منبع بتن</small><strong>{value(row.concreteSourceName||context?.concrete_source_name)}</strong></div><div><small>کلاس بتن</small><strong>{value(row.concreteClass||spec?.concrete_class)}</strong></div><div><small>نمونه‌بردار</small><strong>{value(row.samplerName)}</strong></div><div><small>زمان نمونه‌برداری</small><strong>{isoToPersianLocal(row.sampledAt)}</strong></div><div><small>سن آزمون</small><strong>{row.ageDays==null?'شاهد':`${row.ageDays.toLocaleString('fa-IR')} روز`}</strong></div><div><small>موعد آزمون</small><strong>{isoToPersianLocal(row.dueAt)}</strong></div></div></section>
 <section><h4>طرح و بتن تازه</h4><div className="management-drawer-grid"><div><small>طرح / Revision</small><strong>{row.mixCode?`${row.mixCode}${row.mixRevision!=null?` / R${row.mixRevision}`:''}`:'—'}</strong></div><div><small>عیار سیمان</small><strong>{row.cementKgM3==null?'—':`${row.cementKgM3.toLocaleString('fa-IR')} kg/m³`}</strong></div><div><small>اسلامپ هدف</small><strong>{spec?.target_slump_mm==null?'—':`${spec.target_slump_mm.toLocaleString('fa-IR')} mm`}</strong></div><div><small>اسلامپ واقعی</small><strong>{fresh?.slump_mm==null?'—':`${fresh.slump_mm.toLocaleString('fa-IR')} mm`}</strong></div><div><small>دمای بتن</small><strong>{fresh?.concrete_temperature_c==null?'—':`${fresh.concrete_temperature_c.toLocaleString('fa-IR')} °C`}</strong></div><div><small>زمان بتن تازه</small><strong>{isoToPersianLocal(fresh?.measured_at)}</strong></div><div><small>حجم برنامه‌ریزی‌شده</small><strong>{spec?.planned_volume_m3==null?'—':`${spec.planned_volume_m3.toLocaleString('fa-IR')} m³`}</strong></div><div><small>روش اجرا</small><strong>{value(spec?.placement_method)}</strong></div></div></section>
 <section><h4>نمونه و نتیجه</h4><div className="management-drawer-grid"><div><small>وضعیت نتیجه</small><strong>{stateLabel(row.resultState)}</strong></div><div><small>مقاومت نهایی</small><strong>{mpa(row.strengthMpa)}</strong></div><div><small>زمان آزمون</small><strong>{isoToPersianLocal(row.testedAt)}</strong></div><div><small>آزمایش‌کننده</small><strong>{value(row.testedBy)}</strong></div><div><small>تأییدکننده</small><strong>{value(row.approvedBy)}</strong></div><div><small>شکل نمونه</small><strong>{physics?.shape==='cube'?'مکعبی':physics?.shape==='cylinder'?'استوانه‌ای':'—'}</strong></div><div><small>جرم حجمی</small><strong>{physics?.density_kg_m3==null?'—':`${physics.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³`}</strong></div><div><small>Revision مشخصات</small><strong>{physics?.revision==null?'—':physics.revision.toLocaleString('fa-IR')}</strong></div></div></section>
 <RuleProfileEvaluationPanel projectId={row.projectId} sampleId={row.sampleId} resultRevision={currentApprovedRevision}/>
 <section><div className="management-drawer-section-head"><h4>تاریخچه نتیجه</h4><span>{history.length.toLocaleString('fa-IR')} Revision</span></div>{history.length?<div className="management-drawer-timeline">{history.map(item=><div key={item.revision}><b>R{item.revision.toLocaleString('fa-IR')}</b><span><strong>{stateLabel(item.state)} · {mpa(item.strength_mpa)}</strong><small>{isoToPersianLocal(item.tested_at)} · {value(item.tested_by)}{item.reason?` · ${item.reason}`:''}</small></span></div>)}</div>:<div className="management-drawer-empty">تاریخچه نتیجه‌ای ثبت نشده است.</div>}</section>
 <section><div className="management-drawer-section-head"><h4>آزمایشگاه‌های مقایسه‌ای</h4><span>{external.length.toLocaleString('fa-IR')} نتیجه</span></div>{external.length?<div className="management-drawer-external">{external.map(item=><div key={item.id}><span><strong>{item.laboratory_name}</strong><small>Event: {item.external_event_id}</small></span><span><b>{mpa(item.strength_mpa)}</b><small>{isoToPersianLocal(item.tested_at)} · {(attachmentCounts[item.external_event_id]??0).toLocaleString('fa-IR')} پیوست</small></span></div>)}</div>:<div className="management-drawer-empty">نتیجه مقایسه‌ای برای این نمونه ثبت نشده است.</div>}</section>
 <footer><span>Series ID: {row.seriesId}</span><button type="button" className="secondary-button" onClick={onClose}>بستن پرونده</button></footer></aside></div>;
}
