import {useEffect,useMemo,useState} from 'react';
import type {FormEvent} from 'react';
import type {AnalyticsMetric,AnalyticsSummary,ProjectSummary,StrengthAnalyticsMetric} from '../shared/ipc';
import {PersianDateTimeInput} from './PersianDateTimeInput';
import {currentJalaliYear,previousPeriodicRange,resolvePeriodicRange,type PeriodicPreset} from './periodic-reporting';
import './management-analytics-dashboard.css';

type MetricKey='strength'|'slump'|'concreteTemperature'|'hardenedDensity';
const metricMeta:Record<MetricKey,{title:string;unit:string;scope:string}>={strength:{title:'مقاومت فشاری',unit:'MPa',scope:'فقط نتایج تأییدشده'},slump:{title:'اسلامپ',unit:'mm',scope:'اندازه‌گیری بتن تازه'},concreteTemperature:{title:'دمای بتن',unit:'°C',scope:'اندازه‌گیری بتن تازه'},hardenedDensity:{title:'جرم حجمی بتن سخت‌شده',unit:'kg/m³',scope:'اندازه‌گیری مستقل هر نمونه'}};
function n(value:number|null,digits=2){return value===null?'—':value.toLocaleString('fa-IR',{maximumFractionDigits:digits});}
function delta(current:number|null,previous:number|null){if(current===null||previous===null)return null;if(previous===0)return current===0?0:null;return((current-previous)/Math.abs(previous))*100;}
function previousRange(startAt:string,endAt:string){const start=new Date(startAt).getTime(),end=new Date(endAt).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return null;const duration=end-start,previousEnd=start-1,previousStart=previousEnd-duration;return{startAt:new Date(previousStart).toISOString(),endAt:new Date(previousEnd).toISOString()};}
function Trend({metric}:{metric:AnalyticsMetric}){if(metric.trend.length<2)return <div className="management-empty">داده کافی برای روند نیست.</div>;const values=metric.trend.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),span=max-min||1;const points=metric.trend.map((p,i)=>`${(i/(metric.trend.length-1))*100},${44-((p.value-min)/span)*38}`).join(' ');return <svg className="management-trend" viewBox="0 0 100 48" preserveAspectRatio="none"><polyline points={points} fill="none" vectorEffect="non-scaling-stroke"/></svg>}
function ExecutiveCard({keyName,current,previous}:{keyName:MetricKey;current:AnalyticsMetric;previous:AnalyticsMetric|null}){const meta=metricMeta[keyName],change=delta(current.statistics.mean,previous?.statistics.mean??null);return <article className="management-kpi glass"><div className="management-kpi-head"><div><p className="eyebrow">{meta.unit}</p><h4>{meta.title}</h4></div><span className="management-count">n={current.statistics.count.toLocaleString('fa-IR')}</span></div><div className="management-primary"><strong>{n(current.statistics.mean)}</strong><span className={change===null?'is-neutral':change>0?'is-up':change<0?'is-down':'is-neutral'}>{change===null?'بدون مقایسه':`${change>0?'+':''}${n(change)}٪ نسبت به دوره قبل`}</span></div><Trend metric={current}/><div className="management-mini"><span>کمینه <b>{n(current.statistics.min)}</b></span><span>بیشینه <b>{n(current.statistics.max)}</b></span><span>CV <b>{current.statistics.cvPercent===null?'—':`${n(current.statistics.cvPercent)}٪`}</b></span></div></article>}
function SpecialistReport({keyName,current,previous}:{keyName:MetricKey;current:AnalyticsMetric;previous:AnalyticsMetric|null}){const meta=metricMeta[keyName],s=current.statistics,change=delta(s.mean,previous?.statistics.mean??null),strength=keyName==='strength'?current as StrengthAnalyticsMetric:null;return <article className="specialist-report glass"><div className="specialist-head"><div><p className="eyebrow">Specialized QC Report</p><h4>{meta.title}</h4><span>{meta.scope}</span></div><strong>{n(s.mean)} <small>{meta.unit}</small></strong></div><Trend metric={current}/><div className="specialist-stats"><span>تعداد<b>{s.count.toLocaleString('fa-IR')}</b></span><span>میانگین<b>{n(s.mean)}</b></span><span>کمینه<b>{n(s.min)}</b></span><span>بیشینه<b>{n(s.max)}</b></span><span>انحراف معیار نمونه<b>{n(s.sampleSd)}</b></span><span>CV<b>{s.cvPercent===null?'—':`${n(s.cvPercent)}٪`}</b></span></div><div className="specialist-comparison"><span>تغییر میانگین نسبت به دوره قبل</span><b>{change===null?'داده مقایسه‌ای کافی نیست':`${change>0?'+':''}${n(change)}٪`}</b></div>{strength&&<div className="strength-age-breakdown"><span>تفکیک مقاومت بر حسب سن نمونه</span><div>{Object.entries(strength.byAge).map(([age,stats])=><em key={age}>{age==='witness'?'شاهد':`${Number(age).toLocaleString('fa-IR')} روزه`}<b>{n(stats.mean)} MPa</b><small>n={stats.count.toLocaleString('fa-IR')}</small></em>)}</div></div>}<p className="specialist-note">این بخش تحلیل توصیفی داده‌های ثبت‌شده است و به‌تنهایی حکم پذیرش یا رد استاندارد صادر نمی‌کند.</p></article>}
export function ManagementAnalyticsDashboard({refreshKey=0}:{refreshKey?:number}){
 const [projects,setProjects]=useState<ProjectSummary[]>([]),[current,setCurrent]=useState<AnalyticsSummary|null>(null),[previous,setPrevious]=useState<AnalyticsSummary|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[comparisonLabel,setComparisonLabel]=useState('همه داده‌های موجود'),[preset,setPreset]=useState<PeriodicPreset>('season'),[year,setYear]=useState(currentJalaliYear()),[periodIndex,setPeriodIndex]=useState(1),[projectId,setProjectId]=useState<string|null>(null),[selectedMetric,setSelectedMetric]=useState<MetricKey>('strength');
 useEffect(()=>{void Promise.all([window.tolou.listProjects(),window.tolou.analyticsSummary({})]).then(([p,a])=>{if(!p.ok)throw new Error(p.message);if(!a.ok)throw new Error(a.message);setProjects(p.data.filter(x=>x.archived===0));setCurrent(a.data);setPrevious(null);}).catch(e=>setMessage(e instanceof Error?e.message:'داشبورد مدیریت بارگذاری نشد'));},[refreshKey]);
 async function loadPeriod(startAt:string,endAt:string,priorStart:string,priorEnd:string,label:string){setBusy(true);setMessage('');try{const [c,p]=await Promise.all([window.tolou.analyticsSummary({projectId,startAt,endAt}),window.tolou.analyticsSummary({projectId,startAt:priorStart,endAt:priorEnd})]);if(!c.ok)throw new Error(c.message);if(!p.ok)throw new Error(p.message);setCurrent(c.data);setPrevious(p.data);setComparisonLabel(`${label} · مقایسه با دوره قبل`);}catch(e){setMessage(e instanceof Error?e.message:'گزارش دوره‌ای انجام نشد');}finally{setBusy(false);}}
 async function applyPreset(){try{const range=resolvePeriodicRange(preset,year,preset==='year'?null:periodIndex),prior=previousPeriodicRange(range);await loadPeriod(range.startAt,range.endAt,prior.startAt,prior.endAt,range.label);}catch(e){setMessage(e instanceof Error?e.message:'دوره شمسی معتبر نیست');}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),startAt=String(f.get('startAt')??'')||null,endAt=String(f.get('endAt')??'')||null;if(!startAt||!endAt){setMessage('ابتدا و انتهای بازه سفارشی را تعیین کنید');return;}const prior=previousRange(startAt,endAt);if(!prior){setMessage('بازه زمانی معتبر نیست');return;}await loadPeriod(startAt,endAt,prior.startAt,prior.endAt,'بازه سفارشی');}
 const metrics=useMemo(()=>current?(['strength','slump','concreteTemperature','hardenedDensity'] as MetricKey[]):[],[current]);
 return <section className="management-analytics glass"><div className="panel-heading"><div><p className="eyebrow">Periodic QC Reporting</p><h3>داشبورد مدیریتی و گزارش دوره‌ای</h3></div><span className="count-badge">Shared Analytics Core</span></div><div className="management-preset"><label>پروژه<select value={projectId??''} onChange={e=>setProjectId(e.target.value||null)}><option value="">همه پروژه‌ها</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>نوع دوره<select value={preset} onChange={e=>{setPreset(e.target.value as PeriodicPreset);setPeriodIndex(1);}}><option value="season">فصلی</option><option value="month">ماهانه</option><option value="year">سالانه</option></select></label><label>سال شمسی<input type="number" min="1200" max="1600" value={year} onChange={e=>setYear(Number(e.target.value))}/></label>{preset!=='year'&&<label>{preset==='season'?'فصل':'ماه'}<select value={periodIndex} onChange={e=>setPeriodIndex(Number(e.target.value))}>{Array.from({length:preset==='season'?4:12},(_,i)=><option key={i+1} value={i+1}>{(i+1).toLocaleString('fa-IR')}</option>)}</select></label>}<button className="primary-button" type="button" disabled={busy} onClick={()=>void applyPreset()}>{busy?'در حال ارزیابی…':'ساخت گزارش دوره‌ای'}</button></div><form className="management-filter" onSubmit={submit}><label>بازه سفارشی از<PersianDateTimeInput name="startAt"/></label><label>تا<PersianDateTimeInput name="endAt"/></label><button className="secondary-button" disabled={busy}>گزارش بازه سفارشی</button></form><div className="management-period-note">{comparisonLabel}</div>{message&&<div className="workbench-message" role="status">{message}</div>}{current&&<><div className="management-kpi-grid">{metrics.map(key=><ExecutiveCard key={key} keyName={key} current={current[key]} previous={previous?.[key]??null}/>)}</div><div className="management-summary-strip"><span><b>{current.strength.statistics.count.toLocaleString('fa-IR')}</b> نتیجه مقاومت تأییدشده</span><span><b>{current.slump.statistics.count.toLocaleString('fa-IR')}</b> رکورد اسلامپ</span><span><b>{current.concreteTemperature.statistics.count.toLocaleString('fa-IR')}</b> رکورد دما</span><span><b>{current.hardenedDensity.statistics.count.toLocaleString('fa-IR')}</b> رکورد جرم حجمی</span></div><div className="specialist-selector"><span>گزارش تخصصی پارامتر</span>{metrics.map(key=><button key={key} type="button" className={selectedMetric===key?'is-active':''} onClick={()=>setSelectedMetric(key)}>{metricMeta[key].title}</button>)}</div><SpecialistReport keyName={selectedMetric} current={current[selectedMetric]} previous={previous?.[selectedMetric]??null}/><p className="management-disclaimer">گزارش دوره‌ای فعلاً آماری و توصیفی است؛ هیچ معیار قبولی/رد استانداردی بدون Rule Profile مستند اعمال نمی‌شود.</p></>}</section>;
}
