import {useEffect,useMemo,useState} from 'react';
import type {FormEvent} from 'react';
import type {AnalyticsMetric,AnalyticsSummary,ProjectSummary} from '../shared/ipc';
import {PersianDateTimeInput} from './PersianDateTimeInput';
import './management-analytics-dashboard.css';

type MetricKey='strength'|'slump'|'concreteTemperature'|'hardenedDensity';
const metricMeta:Record<MetricKey,{title:string;unit:string}>={
 strength:{title:'مقاومت فشاری',unit:'MPa'},slump:{title:'اسلامپ',unit:'mm'},concreteTemperature:{title:'دمای بتن',unit:'°C'},hardenedDensity:{title:'جرم حجمی بتن سخت‌شده',unit:'kg/m³'}
};
function n(value:number|null,digits=2){return value===null?'—':value.toLocaleString('fa-IR',{maximumFractionDigits:digits});}
function delta(current:number|null,previous:number|null){if(current===null||previous===null)return null;if(previous===0)return current===0?0:null;return((current-previous)/Math.abs(previous))*100;}
function previousRange(startAt:string,endAt:string){const start=new Date(startAt).getTime(),end=new Date(endAt).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return null;const duration=end-start;const previousEnd=start-1;const previousStart=previousEnd-duration;return{startAt:new Date(previousStart).toISOString(),endAt:new Date(previousEnd).toISOString()};}
function Trend({metric}:{metric:AnalyticsMetric}){if(metric.trend.length<2)return <div className="management-empty">داده کافی برای روند نیست.</div>;const values=metric.trend.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),span=max-min||1;const points=metric.trend.map((p,i)=>`${(i/(metric.trend.length-1))*100},${44-((p.value-min)/span)*38}`).join(' ');return <svg className="management-trend" viewBox="0 0 100 48" preserveAspectRatio="none" role="img" aria-label={`روند ${metric.name}`}><polyline points={points} fill="none" vectorEffect="non-scaling-stroke"/></svg>}
function ExecutiveCard({keyName,current,previous}:{keyName:MetricKey;current:AnalyticsMetric;previous:AnalyticsMetric|null}){const meta=metricMeta[keyName],change=delta(current.statistics.mean,previous?.statistics.mean??null);return <article className="management-kpi glass"><div className="management-kpi-head"><div><p className="eyebrow">{meta.unit}</p><h4>{meta.title}</h4></div><span className="management-count">n={current.statistics.count.toLocaleString('fa-IR')}</span></div><div className="management-primary"><strong>{n(current.statistics.mean)}</strong><span className={change===null?'is-neutral':change>0?'is-up':change<0?'is-down':'is-neutral'}>{change===null?'بدون مقایسه':`${change>0?'+':''}${n(change)}٪ نسبت به دوره قبل`}</span></div><Trend metric={current}/><div className="management-mini"><span>کمینه <b>{n(current.statistics.min)}</b></span><span>بیشینه <b>{n(current.statistics.max)}</b></span><span>CV <b>{current.statistics.cvPercent===null?'—':`${n(current.statistics.cvPercent)}٪`}</b></span></div></article>}

export function ManagementAnalyticsDashboard({refreshKey=0}:{refreshKey?:number}){
 const [projects,setProjects]=useState<ProjectSummary[]>([]),[current,setCurrent]=useState<AnalyticsSummary|null>(null),[previous,setPrevious]=useState<AnalyticsSummary|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[comparisonLabel,setComparisonLabel]=useState('همه داده‌های موجود');
 useEffect(()=>{void Promise.all([window.tolou.listProjects(),window.tolou.analyticsSummary({})]).then(([p,a])=>{if(!p.ok)throw new Error(p.message);if(!a.ok)throw new Error(a.message);setProjects(p.data.filter(x=>x.archived===0));setCurrent(a.data);setPrevious(null);setComparisonLabel('همه داده‌های موجود');}).catch(e=>setMessage(e instanceof Error?e.message:'داشبورد مدیریت بارگذاری نشد'));},[refreshKey]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),projectId=String(f.get('projectId')??'')||null,startAt=String(f.get('startAt')??'')||null,endAt=String(f.get('endAt')??'')||null;setBusy(true);setMessage('');try{const currentResult=await window.tolou.analyticsSummary({projectId,startAt,endAt});if(!currentResult.ok)throw new Error(currentResult.message);setCurrent(currentResult.data);if(startAt&&endAt){const prior=previousRange(startAt,endAt);if(!prior)throw new Error('بازه زمانی معتبر نیست');const previousResult=await window.tolou.analyticsSummary({projectId,...prior});if(!previousResult.ok)throw new Error(previousResult.message);setPrevious(previousResult.data);setComparisonLabel('مقایسه با دوره قبلِ هم‌طول');}else{setPrevious(null);setComparisonLabel('برای مقایسه، ابتدا و انتهای بازه را تعیین کنید');}}catch(e){setMessage(e instanceof Error?e.message:'تحلیل مدیریتی انجام نشد');}finally{setBusy(false);}}
 const metrics=useMemo(()=>current?(['strength','slump','concreteTemperature','hardenedDensity'] as MetricKey[]):[],[current]);
 return <section className="management-analytics glass"><div className="panel-heading"><div><p className="eyebrow">Management Analytics</p><h3>داشبورد مدیریتی کیفیت</h3></div><span className="count-badge">Shared Analytics Core</span></div><form className="management-filter" onSubmit={submit}><label>پروژه<select name="projectId" defaultValue=""><option value="">همه پروژه‌ها</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>از تاریخ<PersianDateTimeInput name="startAt"/></label><label>تا تاریخ<PersianDateTimeInput name="endAt"/></label><button className="primary-button" disabled={busy}>{busy?'در حال ارزیابی…':'ارزیابی دوره'}</button></form><div className="management-period-note">{comparisonLabel}</div>{message&&<div className="workbench-message" role="status">{message}</div>}{current&&<><div className="management-kpi-grid">{metrics.map(key=><ExecutiveCard key={key} keyName={key} current={current[key]} previous={previous?.[key]??null}/>)}</div><div className="management-summary-strip"><span><b>{current.strength.statistics.count.toLocaleString('fa-IR')}</b> نتیجه مقاومت تأییدشده</span><span><b>{current.slump.statistics.count.toLocaleString('fa-IR')}</b> رکورد اسلامپ</span><span><b>{current.concreteTemperature.statistics.count.toLocaleString('fa-IR')}</b> رکورد دما</span><span><b>{current.hardenedDensity.statistics.count.toLocaleString('fa-IR')}</b> رکورد جرم حجمی</span></div><p className="management-disclaimer">این داشبورد فعلاً تحلیل توصیفی و مقایسه‌ای ارائه می‌کند و تا زمان تعریف Rule Profile مستند، هیچ نتیجه قبولی/رد استانداردی صادر نمی‌کند.</p></>}</section>;
}
