import { useEffect, useState } from 'react';
import type { AnalyticsMetric, AnalyticsStatistics, ProjectQcReport, ProjectSummary } from '../shared/ipc';

const n=(value:number|null,digits=1)=>value===null?'—':value.toLocaleString('fa-IR',{maximumFractionDigits:digits});
function Stats({stats,unit}:{stats:AnalyticsStatistics;unit:string}){return <div className="report-stats"><span><b>{stats.count.toLocaleString('fa-IR')}</b>تعداد</span><span><b>{n(stats.mean)}</b>میانگین {unit}</span><span><b>{n(stats.min)}</b>کمینه</span><span><b>{n(stats.max)}</b>بیشینه</span><span><b>{n(stats.cvPercent)}</b>CV %</span></div>}
function Trend({metric}:{metric:AnalyticsMetric}){const points=metric.trend; if(!points.length)return <div className="report-empty">داده‌ای در این بازه ثبت نشده است.</div>;const values=points.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),span=max-min||1;const poly=points.map((p,i)=>`${points.length===1?50:(i/(points.length-1))*100},${88-((p.value-min)/span)*70}`).join(' ');return <svg className="report-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`روند ${metric.name}`}><polyline points={poly}/>{points.map((p,i)=><circle key={`${p.at}-${i}`} cx={points.length===1?50:(i/(points.length-1))*100} cy={88-((p.value-min)/span)*70} r="1.6"/>)}</svg>}
function MetricSection({title,metric}:{title:string;metric:AnalyticsMetric}){return <section className="report-metric"><div className="report-metric-head"><h4>{title}</h4><small>{metric.unit}</small></div><Stats stats={metric.statistics} unit={metric.unit}/><Trend metric={metric}/></section>}
export function ProjectQcReportWorkbench({refreshKey=0}:{refreshKey?:number}){const[projects,setProjects]=useState<ProjectSummary[]>([]);const[projectId,setProjectId]=useState('');const[startAt,setStartAt]=useState('');const[endAt,setEndAt]=useState('');const[report,setReport]=useState<ProjectQcReport|null>(null);const[message,setMessage]=useState('');const[loading,setLoading]=useState(false);
 useEffect(()=>{void window.tolou.listProjects().then(r=>{if(r.ok){const active=r.data.filter(p=>p.archived===0);setProjects(active);setProjectId(v=>v||active[0]?.id||'');}})},[refreshKey]);
 const generate=async()=>{if(!projectId){setMessage('ابتدا پروژه را انتخاب کنید.');return;}setLoading(true);setMessage('');const result=await window.tolou.projectQcReport({projectId,startAt:startAt||null,endAt:endAt||null});setLoading(false);if(!result.ok){setMessage(result.message);return;}setReport(result.data);};
 return <section className="panel panel--wide glass report-workbench"><div className="panel-heading"><div><p className="eyebrow eyebrow--accent">REPORTING</p><h3>گزارش کنترل کیفیت پروژه</h3></div><span className="count-badge">▤</span></div><div className="report-controls no-print"><label>پروژه<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">انتخاب پروژه</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>شروع UTC / ISO<input value={startAt} onChange={e=>setStartAt(e.target.value)} placeholder="2026-09-01T00:00:00Z"/></label><label>پایان UTC / ISO<input value={endAt} onChange={e=>setEndAt(e.target.value)} placeholder="2026-09-30T23:59:59Z"/></label><button className="primary-button" onClick={()=>void generate()} disabled={loading}>{loading?'در حال تهیه…':'تهیه گزارش'}</button>{report&&<button className="secondary-button" onClick={()=>window.print()}>چاپ / ذخیره PDF</button>}</div>{message&&<p className="report-message">{message}</p>}{report&&<article className="print-report"><header className="report-title"><div><p>سامانه طلوع | گزارش مهندسی کنترل کیفیت بتن</p><h2>{report.project.name}</h2><span>{report.company.name}</span></div><div className="report-schema">نسخه گزارش {report.schemaVersion.toLocaleString('fa-IR')}</div></header><div className="report-context"><span><b>کارفرما / مشتری پروژه</b>{report.project.customerName||'—'}</span><span><b>نشانی پروژه</b>{report.project.address||'—'}</span><span><b>سری‌های نمونه‌گیری</b>{report.counts.samplingSeries.toLocaleString('fa-IR')}</span><span><b>نتایج مقاومت تأییدشده</b>{report.counts.approvedStrengthResults.toLocaleString('fa-IR')}</span></div><div className="report-metrics-grid"><MetricSection title="مقاومت فشاری" metric={report.analytics.strength}/><MetricSection title="اسلامپ بتن تازه" metric={report.analytics.slump}/><MetricSection title="دمای بتن تازه" metric={report.analytics.concreteTemperature}/><MetricSection title="جرم حجمی بتن سخت‌شده" metric={report.analytics.hardenedDensity}/></div><footer className="report-notes">{report.notes.map(note=><p key={note}>{note}</p>)}<small>این خروجی توصیفی است؛ معیار قبولی/رد فقط پس از فعال‌سازی Rule Profile مستند قابل اعمال خواهد بود.</small></footer></article>}</section>;
}
