import {useCallback,useEffect,useState} from 'react';
import {isoToPersianLocal} from './jalali';
import './qc-exception-action-center.css';

type ExceptionStatus='open'|'acknowledged'|'resolved';
type ExceptionItem={exceptionKey:string;status:ExceptionStatus;category:string;severity:'info'|'warning'|'critical';projectId:string|null;projectName:string|null;sampleId:string|null;title:string;detail:string;sourceType:string;sourceRef:string|null;observedAt:string;reason:string|null;actor:string;createdAt:string};
type Result<T>={ok:true;data:T}|{ok:false;message:string};
type SyncResult={detected:number;autoResolved:number;open:number;acknowledged:number;resolved:number;items:ExceptionItem[]};
type Bridge={sync:()=>Promise<Result<SyncResult>>;acknowledge:(key:string,reason:string)=>Promise<Result<ExceptionItem>>;resolve:(key:string,reason:string)=>Promise<Result<ExceptionItem>>};
const bridge=()=>((window as unknown as {tolouExceptions:Bridge}).tolouExceptions);
const categoryLabel=(value:string)=>value==='overdue_test'?'آزمون عقب‌افتاده':value==='operational_reference'?'مرجع عملیاتی':value==='statistical_signal'?'سیگنال آماری':'گردش کار';
const severityLabel=(value:string)=>value==='critical'?'بحرانی':value==='warning'?'هشدار':'اطلاع';

export function QcExceptionActionCenter({refreshKey=0,onChanged}:{refreshKey?:number;onChanged?:()=>void}){
 const[data,setData]=useState<SyncResult|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showResolved,setShowResolved]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const r=await bridge().sync();if(!r.ok)throw new Error(r.message);setData(r.data);}catch(e){setMessage(e instanceof Error?e.message:'همگام‌سازی موارد نیازمند اقدام انجام نشد.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load,refreshKey]);
 async function act(item:ExceptionItem,kind:'acknowledge'|'resolve'){const promptText=kind==='resolve'?'دلیل بستن مورد را ثبت کنید:':'یادداشت بررسی/اقدام اولیه را ثبت کنید:';const reason=window.prompt(promptText,'');if(!reason?.trim())return;setBusy(true);setMessage('');try{const r=kind==='resolve'?await bridge().resolve(item.exceptionKey,reason.trim()):await bridge().acknowledge(item.exceptionKey,reason.trim());if(!r.ok)throw new Error(r.message);await load();onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'ثبت اقدام انجام نشد.');}finally{setBusy(false);}}
 if(!data&&!message)return <section className="qc-action-center glass"><div className="qc-action-loading">در حال استخراج موارد نیازمند اقدام…</div></section>;
 const actionable=data?.items.filter(x=>x.status!=='resolved')??[],resolved=data?.items.filter(x=>x.status==='resolved')??[],visible=showResolved?[...actionable,...resolved]:actionable;
 return <section className="qc-action-center glass"><div className="qc-action-head"><div><p className="eyebrow eyebrow--accent">QC ACTION CENTER</p><h3>موارد نیازمند اقدام</h3><p>موارد از داده جاری استخراج می‌شوند؛ ثبت اقدام و بستن هر مورد دارای Audit Trail غیرقابل‌ویرایش است.</p></div><div className="qc-action-summary"><span><b>{(data?.open??0).toLocaleString('fa-IR')}</b> باز</span><span><b>{(data?.acknowledged??0).toLocaleString('fa-IR')}</b> در حال پیگیری</span><span><b>{(data?.resolved??0).toLocaleString('fa-IR')}</b> بسته</span></div></div>{message&&<div className="workbench-message">{message}</div>}<div className="qc-action-toolbar"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void load()}>{busy?'در حال بررسی…':'بازخوانی داده جاری'}</button><label><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/> نمایش موارد بسته‌شده</label>{data&&data.autoResolved>0&&<small>{data.autoResolved.toLocaleString('fa-IR')} مورد به‌دلیل رفع شرط ایجاد، خودکار بسته شد.</small>}</div>{visible.length?<div className="qc-action-list">{visible.map(item=><article className={`qc-action-item qc-action-item--${item.severity}`} key={item.exceptionKey}><div className="qc-action-item-main"><div className="qc-action-item-tags"><span>{categoryLabel(item.category)}</span><i>{severityLabel(item.severity)}</i><em>{item.status==='open'?'باز':item.status==='acknowledged'?'در حال پیگیری':'بسته'}</em></div><h4>{item.title}</h4><p>{item.detail}</p><small>{item.projectName||'کنترل داخلی'}{item.sampleId?` · Sample ${item.sampleId}`:''} · مشاهده: {isoToPersianLocal(item.observedAt)}</small>{item.reason&&<small>آخرین اقدام: {item.reason}</small>}</div><div className="qc-action-item-actions">{item.status==='open'&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>void act(item,'acknowledge')}>ثبت بررسی</button>}{item.status!=='resolved'&&<button type="button" className="primary-button" disabled={busy} onClick={()=>void act(item,'resolve')}>بستن مورد</button>}</div></article>)}</div>:<div className="qc-action-empty">در داده‌های جاری مورد باز یا در حال پیگیری وجود ندارد.</div>}<div className="qc-action-policy">هشدار «زیر مرجع عملیاتی» معیار پذیرش استانداردی نیست. سیگنال سه‌سیگما نیز صرفاً نشانه آماری توصیفی است و به‌تنهایی علت یا عدم انطباق را اثبات نمی‌کند.</div></section>;
}
