import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import type { SampleSummary, SpecimenPhysicsSummary, SpecimenShape } from '../shared/ipc';
import { PersianDateTimeInput } from './PersianDateTimeInput';
import { isoToPersianLocal } from './jalali';
import './laboratory-workbench.css';

type Step='select'|'physics'|'strength';
type ComparisonParty={id:string;series_id:string;party_type:string;party_name:string;laboratory_name:string|null;sampler_name:string|null;external_reference:string|null;notes:string|null};
type ComparisonResult={result_id:string;revision:number;series_id:string;comparison_party_id:string;party_name:string;laboratory_name:string|null;age_days:number|null;specimen_label:string;strength_mpa:number;tested_at:string;tested_by:string|null;notes:string|null;reason:string|null};
type MixSnapshot={mixCode:string|null;mixRevision:number|null;characteristicStrengthMpa:number|null;targetStrengthMpa:number|null;declaredWaterCementRatio:number|null;calculatedWaterCementRatio:number|null;waterCementMismatch:boolean;cementKgM3:number|null;waterKgM3:number|null;totalRecordedMassKgM3:number};
type TraceabilityBridge={listComparisonParties:(seriesId:string)=>Promise<{ok:boolean;data?:ComparisonParty[];message?:string}>;listComparisonResults:(seriesId:string)=>Promise<{ok:boolean;data?:ComparisonResult[];message?:string}>;saveComparisonResult:(input:{resultId:string;seriesId:string;comparisonPartyId:string;expectedRevision:number;ageDays:number|null;specimenLabel:string;strengthMpa:number;testedAt:string;testedBy?:string;notes?:string;reason?:string})=>Promise<{ok:boolean;data?:unknown;message?:string}>;getMixSnapshot:(seriesId:string)=>Promise<{ok:boolean;data?:MixSnapshot|null;message?:string}>};
const traceability=()=>((window as unknown as {tolouTraceability:TraceabilityBridge}).tolouTraceability);
const nextComparisonResultId=()=>`CMPR-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const average=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;

export function ResultEntryWorkspace({onChanged,refreshKey=0}:{onChanged?:()=>void;refreshKey?:number}){
  const[allSamples,setAllSamples]=useState<SampleSummary[]>([]);
  const[sampleId,setSampleId]=useState('');
  const[physics,setPhysics]=useState<SpecimenPhysicsSummary|null>(null);
  const[shape,setShape]=useState<SpecimenShape>('cube');
  const[step,setStep]=useState<Step>('select');
  const[busy,setBusy]=useState(false);
  const[message,setMessage]=useState('');
  const[comparisonParties,setComparisonParties]=useState<ComparisonParty[]>([]);
  const[comparisonResults,setComparisonResults]=useState<ComparisonResult[]>([]);
  const[comparisonPartyId,setComparisonPartyId]=useState('');
  const[mixSnapshot,setMixSnapshot]=useState<MixSnapshot|null>(null);

  async function reload(){const result=await window.tolou.listSamples(300);if(!result.ok)throw new Error(result.message);const pending=result.data.filter(x=>x.due_at!==null&&x.state!=='approved'&&x.state!=='void');setAllSamples(pending);const dueNow=pending.filter(x=>x.due_at&&Date.parse(x.due_at)<=Date.now());setSampleId(current=>dueNow.some(x=>x.id===current)?current:(dueNow[0]?.id??''));}
  useEffect(()=>{void reload().catch(e=>setMessage(e instanceof Error?e.message:'بارگذاری نمونه‌ها انجام نشد'));},[refreshKey]);
  const dueSamples=useMemo(()=>allSamples.filter(x=>x.due_at&&Date.parse(x.due_at)<=Date.now()),[allSamples]);
  const futureSamples=useMemo(()=>allSamples.filter(x=>x.due_at&&Date.parse(x.due_at)>Date.now()).sort((a,b)=>a.due_at!.localeCompare(b.due_at!)),[allSamples]);
  const selected=useMemo(()=>dueSamples.find(x=>x.id===sampleId),[dueSamples,sampleId]);

  async function loadTraceability(seriesId:string){const [p,r,m]=await Promise.all([traceability().listComparisonParties(seriesId),traceability().listComparisonResults(seriesId),traceability().getMixSnapshot(seriesId)]);if(!p.ok)throw new Error(p.message||'طرف مقایسه‌ای بارگذاری نشد');if(!r.ok)throw new Error(r.message||'نتایج مقایسه‌ای بارگذاری نشد');if(!m.ok)throw new Error(m.message||'طرح مخلوط نوبت بارگذاری نشد');const parties=p.data??[];setComparisonParties(parties);setComparisonResults(r.data??[]);setComparisonPartyId(current=>parties.some(x=>x.id===current)?current:(parties[0]?.id??''));setMixSnapshot(m.data??null);}
  useEffect(()=>{if(!sampleId){setPhysics(null);setComparisonParties([]);setComparisonResults([]);setMixSnapshot(null);return;}const sample=dueSamples.find(x=>x.id===sampleId);void Promise.all([window.tolou.getSpecimenPhysics(sampleId),sample?loadTraceability(sample.series_id):Promise.resolve()]).then(([r])=>{if(!r.ok)throw new Error(r.message);setPhysics(r.data);setShape(r.data?.shape??'cube');}).catch(e=>setMessage(e instanceof Error?e.message:'بارگذاری پرونده نمونه انجام نشد'));},[sampleId,refreshKey,dueSamples]);

  const comparisonForAge=useMemo(()=>selected?comparisonResults.filter(x=>x.age_days===selected.age_days):[],[comparisonResults,selected]);
  const comparisonByParty=useMemo(()=>comparisonParties.map(p=>{const rows=comparisonForAge.filter(r=>r.comparison_party_id===p.id);return{party:p,rows,mean:average(rows.map(r=>r.strength_mpa))};}),[comparisonParties,comparisonForAge]);

  async function savePhysics(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);setBusy(true);setMessage('');try{const result=await window.tolou.saveSpecimenPhysics({sampleId:selected.id,expectedRevision:physics?.revision??0,shape,lengthMm:shape==='cube'?Number(data.get('lengthMm')):null,widthMm:shape==='cube'?Number(data.get('widthMm')):null,heightMm:Number(data.get('heightMm')),diameterMm:shape==='cylinder'?Number(data.get('diameterMm')):null,massKg:Number(data.get('massKg')),reason:physics?String(data.get('reason')??''):undefined});if(!result.ok)throw new Error(result.message);const current=await window.tolou.getSpecimenPhysics(selected.id);if(current.ok)setPhysics(current.data);setMessage(`مشخصات فیزیکی ثبت شد. جرم حجمی محاسبه‌شده: ${result.data.densityKgM3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³`);setStep('strength');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'ثبت مشخصات فیزیکی انجام نشد');}finally{setBusy(false);}}

  async function saveStrength(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const data=new FormData(event.currentTarget);setBusy(true);setMessage('');try{const testedAt=String(data.get('testedAt')??'');if(!testedAt)throw new Error('زمان آزمون را وارد کنید.');const result=await window.tolou.saveDraft({sampleId:selected.id,expectedRevision:selected.revision??0,strengthMpa:Number(data.get('strengthMpa')),testedAt,testedBy:String(data.get('testedBy')??''),reason:String(data.get('reason')??'')});if(!result.ok)throw new Error(result.message);setMessage('نتیجه مقاومت به‌صورت پیش‌نویس ذخیره شد و اکنون در بخش «بررسی و تأیید» قابل رسیدگی است.');await reload();setStep('select');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'ثبت نتیجه انجام نشد');}finally{setBusy(false);}}

  async function saveComparison(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||!comparisonPartyId)return;const form=event.currentTarget,data=new FormData(form);setBusy(true);setMessage('');try{const testedAt=String(data.get('comparisonTestedAt')??'');if(!testedAt)throw new Error('زمان آزمون طرف مقابل را وارد کنید.');const result=await traceability().saveComparisonResult({resultId:nextComparisonResultId(),seriesId:selected.series_id,comparisonPartyId,expectedRevision:0,ageDays:selected.age_days,specimenLabel:String(data.get('comparisonSpecimenLabel')??''),strengthMpa:Number(data.get('comparisonStrengthMpa')),testedAt,testedBy:String(data.get('comparisonTestedBy')??''),notes:String(data.get('comparisonNotes')??'')});if(!result.ok)throw new Error(result.message||'ثبت نتیجه طرف مقابل انجام نشد');await loadTraceability(selected.series_id);form.reset();setMessage('نتیجه طرف مقابل به همین نوبت نمونه‌برداری متصل و ثبت شد.');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'ثبت نتیجه مقایسه‌ای انجام نشد');}finally{setBusy(false);}}

  const mixLabel=mixSnapshot?`${mixSnapshot.mixCode??'طرح بدون کد'}${mixSnapshot.mixRevision!==null?` / R${mixSnapshot.mixRevision}`:''}`:'ثبت نشده';
  return <>
    <section className="workspace-intro"><p className="eyebrow">آزمون مقاومت</p><h2>ثبت نتیجه آزمون</h2><p>نتایج مجموعه شما و نتایج نمونه‌های متناظر طرف مقابل در همان پرونده نمونه‌برداری ثبت می‌شوند تا مقایسه قابل ردیابی باشد.</p></section>
    <section className="workbench glass panel--wide">
      {message&&<div className="workbench-message" role="status">{message}</div>}
      {!dueSamples.length?<div className="recovery-empty"><h3>امروز نمونه‌ای برای ثبت نتیجه ندارید</h3><p>{futureSamples.length?`نزدیک‌ترین موعد آینده: ${isoToPersianLocal(futureSamples[0].due_at)}`:'پس از ثبت نمونه‌برداری، موعدها در این بخش نمایش داده می‌شوند.'}</p></div>:<>
        <div className="result-stepper" aria-label="مراحل ثبت نتیجه"><button type="button" className={step==='select'?'is-active':''} onClick={()=>setStep('select')}>۱. انتخاب نمونه</button><button type="button" className={step==='physics'?'is-active':''} disabled={!selected} onClick={()=>setStep('physics')}>۲. ابعاد، جرم و جرم حجمی</button><button type="button" className={step==='strength'?'is-active':''} disabled={!selected} onClick={()=>setStep('strength')}>۳. مقاومت و مقایسه</button></div>
        {step==='select'&&<div className="workbench-form"><label>نمونه موعدرسیده<select value={sampleId} onChange={e=>{setSampleId(e.target.value);setStep('select');}} required>{dueSamples.map(sample=><option key={sample.id} value={sample.id}>{sample.project_name??sample.title??'نمونه آزمایشگاه'} — {sample.age_days===null?'شاهد':`${sample.age_days.toLocaleString('fa-IR')} روزه`} — {isoToPersianLocal(sample.due_at)}</option>)}</select></label>{selected&&<div className="result-context result-context--wide"><div><small>پروژه / سری</small><strong>{selected.project_name??selected.title??'نمونه آزمایشگاه'}</strong></div><div><small>سن نمونه</small><strong>{selected.age_days===null?'شاهد':`${selected.age_days.toLocaleString('fa-IR')} روزه`}</strong></div><div><small>طرح مخلوط نوبت</small><strong>{mixLabel}</strong></div><div><small>طرف مقایسه‌ای</small><strong>{comparisonParties.length?`${comparisonParties.length.toLocaleString('fa-IR')} طرف`:'ندارد'}</strong></div></div>}<div className="row-actions"><button type="button" className="primary-button" onClick={()=>setStep('physics')}>ادامه: مشخصات فیزیکی</button><button type="button" className="secondary-button" onClick={()=>setStep('strength')}>رفتن مستقیم به مقاومت</button></div></div>}
        {step==='physics'&&selected&&<form key={`${selected.id}-${physics?.revision??0}`} className="workbench-form" onSubmit={savePhysics}><div className="history-strip"><strong>{selected.project_name??selected.title??'نمونه آزمایشگاه'}</strong><span>{selected.age_days===null?'شاهد':`${selected.age_days.toLocaleString('fa-IR')} روزه`}</span>{physics&&<span>جرم حجمی فعلی: {physics.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³</span>}</div><label>شکل نمونه<select value={shape} onChange={e=>setShape(e.target.value as SpecimenShape)}><option value="cube">مکعبی</option><option value="cylinder">استوانه‌ای</option></select></label>{shape==='cube'?<><label>طول واقعی (mm)<input name="lengthMm" type="number" min="0.01" step="0.01" defaultValue={physics?.length_mm??150} required/></label><label>عرض واقعی (mm)<input name="widthMm" type="number" min="0.01" step="0.01" defaultValue={physics?.width_mm??150} required/></label></>:<label>قطر واقعی (mm)<input name="diameterMm" type="number" min="0.01" step="0.01" defaultValue={physics?.diameter_mm??150} required/></label>}<label>ارتفاع واقعی (mm)<input name="heightMm" type="number" min="0.01" step="0.01" defaultValue={physics?.height_mm??(shape==='cube'?150:300)} required/></label><label>جرم نمونه (kg)<input name="massKg" type="number" min="0.001" step="0.001" defaultValue={physics?.mass_kg??''} required/></label>{physics&&<label>علت اصلاح<textarea name="reason" required placeholder="علت اصلاح ابعاد یا جرم قبلی"/></label>}<div className="form-help">حجم و جرم حجمی توسط موتور محاسباتی نرم‌افزار از ابعاد واقعی و جرم نمونه محاسبه می‌شود.</div><div className="row-actions"><button className="primary-button" disabled={busy}>{busy?'در حال محاسبه و ثبت…':physics?'محاسبه و ثبت اصلاح':'محاسبه و ثبت جرم حجمی'}</button><button type="button" className="secondary-button" onClick={()=>setStep('strength')}>مرحله مقاومت</button></div></form>}
        {step==='strength'&&selected&&<div className="result-strength-layout"><form className="workbench-form result-own-form" onSubmit={saveStrength}><div className="result-context result-context--wide"><div><small>نمونه ما</small><strong>{selected.project_name??selected.title??'نمونه آزمایشگاه'}</strong></div><div><small>سن</small><strong>{selected.age_days===null?'شاهد':`${selected.age_days.toLocaleString('fa-IR')} روزه`}</strong></div><div><small>طرح مخلوط</small><strong>{mixLabel}</strong></div><div><small>جرم حجمی</small><strong>{physics?`${physics.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³`:'ثبت نشده'}</strong></div></div>{!physics&&<div className="workbench-message">مشخصات فیزیکی این نمونه هنوز ثبت نشده است.</div>}<label>مقاومت فشاری ما (MPa)<input name="strengthMpa" type="number" min="0" step="0.1" required/></label><label>زمان آزمون (شمسی)<PersianDateTimeInput name="testedAt" required/></label><label>آزمایش‌کننده<input name="testedBy" required/></label>{(selected.revision??0)>0&&<label>علت اصلاح<textarea name="reason" required placeholder="علت اصلاح نتیجه قبلی"/></label>}<div className="row-actions"><button className="primary-button workbench-submit" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره پیش‌نویس نتیجه ما'}</button><button type="button" className="secondary-button" onClick={()=>setStep('physics')}>بازگشت به جرم حجمی</button></div></form>
        <section className="comparison-result-panel"><div className="panel-heading"><div><p className="eyebrow">نمونه متناظر</p><h3>نتایج طرف مقابل</h3></div><span className="count-badge">{comparisonForAge.length.toLocaleString('fa-IR')}</span></div>{!comparisonParties.length?<div className="project-mini-empty">برای این نوبت، طرف مقایسه‌ای ثبت نشده است.</div>:<><form className="comparison-result-form" onSubmit={saveComparison}><label>طرف مقابل<select value={comparisonPartyId} onChange={e=>setComparisonPartyId(e.target.value)} required>{comparisonParties.map(p=><option key={p.id} value={p.id}>{p.party_name}{p.laboratory_name?` — ${p.laboratory_name}`:''}</option>)}</select></label><label>شناسه نمونه طرف مقابل<input name="comparisonSpecimenLabel" placeholder="مثلاً 28-A یا Cube-1" required/></label><label>مقاومت (MPa)<input name="comparisonStrengthMpa" type="number" min="0" step="0.1" required/></label><label>زمان آزمون (شمسی)<PersianDateTimeInput name="comparisonTestedAt" required/></label><label>آزمایش‌کننده طرف مقابل<input name="comparisonTestedBy" placeholder="اختیاری"/></label><label>توضیحات<input name="comparisonNotes" placeholder="شماره گزارش یا توضیح تکمیلی"/></label><button className="secondary-button" disabled={busy}>ثبت نتیجه مقایسه‌ای</button></form><div className="comparison-party-summary">{comparisonByParty.map(group=><article key={group.party.id}><div><strong>{group.party.party_name}</strong><small>{group.party.laboratory_name??group.party.party_type}</small></div><span>{group.rows.length.toLocaleString('fa-IR')} نتیجه</span><b>{group.mean===null?'—':`${group.mean.toLocaleString('fa-IR',{maximumFractionDigits:2})} MPa`}</b></article>)}</div>{comparisonForAge.length>0&&<div className="table-wrap"><table><thead><tr><th>طرف مقابل</th><th>نمونه</th><th>مقاومت</th><th>تاریخ آزمون</th><th>آزمایش‌کننده</th></tr></thead><tbody>{comparisonForAge.map(r=><tr key={r.result_id}><td>{r.party_name}</td><td>{r.specimen_label}</td><td>{r.strength_mpa.toLocaleString('fa-IR',{maximumFractionDigits:2})} MPa</td><td>{isoToPersianLocal(r.tested_at)}</td><td>{r.tested_by??'—'}</td></tr>)}</tbody></table></div>}</>}</section></div>}
      </>}
      {futureSamples.length>0&&<div className="future-schedule"><div className="panel-heading"><div><p className="eyebrow">آینده</p><h3>نمونه‌هایی که هنوز موعدشان نرسیده</h3></div><span className="count-badge">{futureSamples.length.toLocaleString('fa-IR')}</span></div>{futureSamples.slice(0,8).map(sample=><div className="future-schedule-row" key={sample.id}><strong>{sample.project_name??sample.title??'نمونه آزمایشگاه'}</strong><span>{sample.age_days===null?'شاهد':`${sample.age_days.toLocaleString('fa-IR')} روزه`}</span><small>{isoToPersianLocal(sample.due_at)}</small></div>)}</div>}
    </section>
  </>;
}
