import { useEffect, useMemo, useState } from 'react';
import './rule-profile-evaluation.css';

type IpcResult<T>={ok:true;data:T}|{ok:false;message:string};
type RuleProfile={id:string;code:string;title:string;authority:string;document_code:string;document_version:string;status:'draft'|'active'|'retired'};
type ProjectAssignment={project_id:string;profile_id:string;assigned_at:string;assigned_by:string;code:string;title:string;authority:string;document_code:string;document_version:string;status:string};
type EvaluationItem={rule_id?:string;ruleId?:string;rule_key?:string;ruleKey?:string;rule_version?:number;ruleVersion?:number;rule_type?:string;ruleType?:string;reference_clause?:string;referenceClause?:string;source_title?:string;sourceTitle?:string;source_version?:string;sourceVersion?:string;status:'pass'|'fail'|'not_evaluated';message:string;calculation:Record<string,unknown>};
type Evaluation={evaluated:boolean;reused?:boolean;reason?:string;evaluationId?:string;id?:string;overallStatus?:'pass'|'fail'|'not_evaluated';overall_status?:'pass'|'fail'|'not_evaluated';profileCode?:string;profile_code?:string;documentCode?:string;profile_document_code?:string;documentVersion?:string;profile_document_version?:string;evaluated_at?:string;items?:EvaluationItem[]};
type RulesBridge={listProfiles:()=>Promise<IpcResult<RuleProfile[]>>;getProjectAssignment:(projectId:string)=>Promise<IpcResult<ProjectAssignment|null>>;assignProjectProfile:(input:{projectId:string;profileId:string})=>Promise<IpcResult<{projectId:string;profileId:string;assignedAt:string}>>;evaluateResult:(input:{sampleId:string;resultRevision:number})=>Promise<IpcResult<Evaluation>>};
const rules=()=>((window as unknown as {tolouRules:RulesBridge}).tolouRules);
const statusLabel=(status:string|undefined)=>status==='pass'?'برآورده شد':status==='fail'?'برآورده نشد':status==='not_evaluated'?'ارزیابی نشد':'—';
const itemField=(item:EvaluationItem,camel:keyof EvaluationItem,snake:keyof EvaluationItem)=>String(item[camel]??item[snake]??'—');

export function RuleProfileEvaluationPanel({projectId,sampleId,resultRevision}:{projectId:string|null;sampleId:string;resultRevision:number|null}){
 const[profiles,setProfiles]=useState<RuleProfile[]>([]);const[assignment,setAssignment]=useState<ProjectAssignment|null>(null);const[selected,setSelected]=useState('');const[evaluation,setEvaluation]=useState<Evaluation|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const activeProfiles=useMemo(()=>profiles.filter(p=>p.status==='active'),[profiles]);
 async function reload(){if(!projectId)return;const[p,a]=await Promise.all([rules().listProfiles(),rules().getProjectAssignment(projectId)]);if(!p.ok)throw new Error(p.message);if(!a.ok)throw new Error(a.message);setProfiles(p.data);setAssignment(a.data);setSelected(a.data?.profile_id??'');}
 useEffect(()=>{setEvaluation(null);setMessage('');if(!projectId){setProfiles([]);setAssignment(null);setSelected('');return;}void reload().catch(e=>setMessage(e instanceof Error?e.message:'Rule Profile بارگذاری نشد.'));},[projectId,sampleId,resultRevision]);
 async function assign(){if(!projectId||!selected)return;setBusy(true);setMessage('');try{const r=await rules().assignProjectProfile({projectId,profileId:selected});if(!r.ok)throw new Error(r.message);await reload();setEvaluation(null);setMessage('Rule Profile فعال به پروژه متصل شد.');}catch(e){setMessage(e instanceof Error?e.message:'تخصیص Rule Profile انجام نشد.');}finally{setBusy(false);}}
 async function evaluate(){if(!resultRevision)return;setBusy(true);setMessage('');try{const r=await rules().evaluateResult({sampleId,resultRevision});if(!r.ok)throw new Error(r.message);setEvaluation(r.data);if(!r.data.evaluated)setMessage(r.data.reason==='no_profile'?'برای این پروژه Rule Profile تخصیص داده نشده است.':r.data.reason==='no_rules'?'Rule قابل اجرا در پروفایل یافت نشد.':'ارزیابی انجام نشد.');}catch(e){setMessage(e instanceof Error?e.message:'ارزیابی Rule Profile انجام نشد.');}finally{setBusy(false);}}
 if(!projectId)return <section className="rule-evaluation-panel"><h4>Rule Profile</h4><div className="rule-evaluation-empty">این نمونه به پروژه متصل نیست؛ ارزیابی Rule Profile اجرا نمی‌شود.</div></section>;
 const overall=evaluation?.overallStatus??evaluation?.overall_status;const items=evaluation?.items??[];
 return <section className="rule-evaluation-panel"><div className="management-drawer-section-head"><h4>Rule Profile و ارزیابی</h4><span>{assignment?`${assignment.code} / ${assignment.document_version}`:'بدون پروفایل'}</span></div>
  <div className="rule-profile-card"><div><small>پروفایل پروژه</small><strong>{assignment?assignment.title:'تخصیص داده نشده'}</strong>{assignment&&<em>{assignment.authority} · {assignment.document_code} · {assignment.document_version}</em>}</div><div className="rule-profile-controls"><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="">انتخاب Rule Profile فعال</option>{activeProfiles.map(p=><option key={p.id} value={p.id}>{p.code} — {p.title} ({p.document_version})</option>)}</select><button type="button" className="secondary-button" disabled={busy||!selected||selected===assignment?.profile_id} onClick={()=>void assign()}>تخصیص به پروژه</button></div></div>
  {!activeProfiles.length&&<div className="rule-evaluation-empty">هیچ Rule Profile فعال و قابل تخصیصی وجود ندارد.</div>}
  <div className="rule-evaluation-action"><div><small>Result Revision</small><strong>{resultRevision==null?'نتیجه جاری تأییدشده نیست':`R${resultRevision.toLocaleString('fa-IR')}`}</strong></div><button type="button" className="primary-button mini-button" disabled={busy||!assignment||resultRevision==null} onClick={()=>void evaluate()}>{busy?'در حال پردازش…':'اجرای ارزیابی Rule Profile'}</button></div>
  {message&&<div className="rule-evaluation-message">{message}</div>}
  {evaluation?.evaluated&&<div className="rule-evaluation-result"><div className={`rule-evaluation-overall is-${overall}`}><span>نتیجه Rule Profile</span><strong>{statusLabel(overall)}</strong><small>{evaluation.reused?'Snapshot ثبت‌شده بازیابی شد':'Snapshot ارزیابی ثبت شد'} · {evaluation.profileCode??evaluation.profile_code??assignment?.code}</small></div>{items.map((item,index)=><article key={`${item.ruleId??item.rule_id??index}`}><div><strong>{itemField(item,'ruleKey','rule_key')}</strong><span className={`is-${item.status}`}>{statusLabel(item.status)}</span></div><p>{item.message}</p><small>{itemField(item,'sourceTitle','source_title')} · نسخه {itemField(item,'sourceVersion','source_version')} · بند {itemField(item,'referenceClause','reference_clause')}</small></article>)}</div>}
 </section>;
}
