import { useEffect, useState, type FormEvent } from 'react';
import './rule-profile-workspace.css';

type ApiResult<T>={ok:true;data:T}|{ok:false;message:string};
type Profile={id:string;code:string;title:string;authority:string;document_code:string;document_version:string;effective_date:string|null;scope:string;status:'draft'|'active'|'retired'};
type Rule={id:string;rule_key:string;rule_version:number;rule_type:string;parameters:Record<string,unknown>;reference_clause:string;source_title:string;source_version:string;verification_status:string;test_case_count:number;enabled:number;notes:string};
type Detail={profile:Profile;rules:Rule[]};
type RulesApi={listProfiles:()=>Promise<ApiResult<Profile[]>>;getProfile:(id:string)=>Promise<ApiResult<Detail>>;createProfile:(input:unknown)=>Promise<ApiResult<unknown>>;addRule:(input:unknown)=>Promise<ApiResult<unknown>>;verifyRule:(input:unknown)=>Promise<ApiResult<unknown>>;activateProfile:(id:string)=>Promise<ApiResult<unknown>>;retireProfile:(id:string)=>Promise<ApiResult<unknown>>};
const api=()=>((window as unknown as {tolouRules:RulesApi}).tolouRules);
const id=(prefix:string)=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const statusLabel=(s:string)=>s==='draft'?'پیش‌نویس':s==='active'?'فعال':'بازنشسته';

export function RuleProfileWorkspace({onChanged}:{onChanged?:()=>void}){
 const[profiles,setProfiles]=useState<Profile[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),[showRule,setShowRule]=useState(false);
 async function reload(preferred?:string){const r=await api().listProfiles();if(!r.ok)throw new Error(r.message);setProfiles(r.data);const next=preferred??selected??r.data[0]?.id??'';if(next){setSelected(next);const d=await api().getProfile(next);if(!d.ok)throw new Error(d.message);setDetail(d.data);}else setDetail(null);}
 useEffect(()=>{void reload().catch(e=>setMessage(e instanceof Error?e.message:'بارگذاری Rule Profile انجام نشد.'));},[]);
 async function choose(profileId:string){setSelected(profileId);setMessage('');const r=await api().getProfile(profileId);if(r.ok)setDetail(r.data);else setMessage(r.message);}
 async function createProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);setMessage('');try{const profileId=id('RULEPROFILE');const r=await api().createProfile({id:profileId,code:String(d.get('code')),title:String(d.get('title')),authority:String(d.get('authority')),documentCode:String(d.get('documentCode')),documentVersion:String(d.get('documentVersion')),effectiveDate:String(d.get('effectiveDate')??''),scope:'compressive_strength',notes:String(d.get('notes')??'')});if(!r.ok)throw new Error(r.message);await reload(profileId);setShowNew(false);form.reset();setMessage('پروفایل به‌صورت پیش‌نویس ساخته شد. قبل از فعال‌سازی قواعد مستند را اضافه و Verify کنید.');onChanged?.();}catch(err){setMessage(err instanceof Error?err.message:'ساخت پروفایل انجام نشد.');}finally{setBusy(false);}}
 async function addRule(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!detail)return;const form=e.currentTarget,d=new FormData(form);setBusy(true);setMessage('');try{let parameters:Record<string,unknown>;try{parameters=JSON.parse(String(d.get('parameters')));}catch{throw new Error('پارامترهای Rule باید JSON معتبر باشند.');}const r=await api().addRule({id:id('RULE'),profileId:detail.profile.id,ruleKey:String(d.get('ruleKey')),ruleVersion:Number(d.get('ruleVersion')),ruleType:String(d.get('ruleType')),parameters,referenceClause:String(d.get('referenceClause')),sourceTitle:String(d.get('sourceTitle')),sourceVersion:String(d.get('sourceVersion')),notes:String(d.get('notes')??'')});if(!r.ok)throw new Error(r.message);await reload(detail.profile.id);setShowRule(false);form.reset();setMessage('Rule ثبت شد؛ برای فعال‌سازی Profile باید تست‌های آن Verify شوند.');onChanged?.();}catch(err){setMessage(err instanceof Error?err.message:'ثبت Rule انجام نشد.');}finally{setBusy(false);}}
 async function verify(rule:Rule){if(!detail)return;const raw=window.prompt('تعداد Test Case تأییدشده برای این Rule را وارد کنید:','1');if(raw==null)return;const count=Number(raw);setBusy(true);try{const r=await api().verifyRule({profileId:detail.profile.id,ruleId:rule.id,testCaseCount:count});if(!r.ok)throw new Error(r.message);await reload(detail.profile.id);setMessage('Rule با تعداد Test Case ثبت‌شده Verify شد.');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'Verify انجام نشد.');}finally{setBusy(false);}}
 async function activate(){if(!detail||!window.confirm('پس از فعال‌سازی، Profile و Ruleهای آن immutable می‌شوند. ادامه می‌دهید؟'))return;setBusy(true);try{const r=await api().activateProfile(detail.profile.id);if(!r.ok)throw new Error(r.message);await reload(detail.profile.id);setMessage('Rule Profile فعال شد و از این لحظه immutable است.');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'فعال‌سازی انجام نشد.');}finally{setBusy(false);}}
 async function retire(){if(!detail||!window.confirm('Profile فعال بازنشسته شود؟ Profile تخصیص‌یافته به پروژه قابل بازنشسته‌سازی نیست.'))return;setBusy(true);try{const r=await api().retireProfile(detail.profile.id);if(!r.ok)throw new Error(r.message);await reload(detail.profile.id);setMessage('Profile بازنشسته شد. Snapshotهای قبلی بدون تغییر باقی می‌مانند.');onChanged?.();}catch(e){setMessage(e instanceof Error?e.message:'بازنشسته‌سازی انجام نشد.');}finally{setBusy(false);}}
 const ready=detail?.rules.length&&detail.rules.every(r=>r.enabled===1&&r.verification_status==='verified'&&r.test_case_count>0&&r.reference_clause&&r.source_title&&r.source_version);
 return <section className="rule-profile-workspace glass"><div className="panel-heading"><div><p className="eyebrow eyebrow--accent">ENGINEERING GOVERNANCE</p><h2>Rule Profileها</h2><p>قواعد ارزیابی مهندسی فقط با منبع، نسخه، بند مرجع و تست تأییدشده وارد چرخه عملیاتی می‌شوند.</p></div><button className="primary-button" type="button" onClick={()=>setShowNew(v=>!v)}>پروفایل جدید</button></div>{message&&<div className="workbench-message">{message}</div>}
 {showNew&&<form className="rule-profile-form" onSubmit={createProfile}><label>کد Profile<input name="code" required placeholder="مثلاً COMPANY-CS-01"/></label><label>عنوان<input name="title" required/></label><label>مرجع / Authority<input name="authority" required/></label><label>کد سند<input name="documentCode" required/></label><label>نسخه سند<input name="documentVersion" required/></label><label>تاریخ اثرگذاری<input name="effectiveDate" placeholder="YYYY-MM-DD"/></label><label className="span-2">یادداشت<input name="notes"/></label><button className="primary-button" disabled={busy}>ساخت Draft</button></form>}
 <div className="rule-profile-layout"><aside className="rule-profile-list">{profiles.length===0?<div className="rule-empty">هنوز Profile تعریف نشده است.</div>:profiles.map(p=><button key={p.id} className={selected===p.id?'is-active':''} onClick={()=>void choose(p.id)}><span><strong>{p.code}</strong><small>{p.title}</small></span><i className={`rule-status rule-status--${p.status}`}>{statusLabel(p.status)}</i></button>)}</aside><main className="rule-profile-detail">{!detail?<div className="rule-empty">یک Profile را انتخاب کنید.</div>:<><div className="rule-profile-hero"><div><small>{detail.profile.authority}</small><h3>{detail.profile.title}</h3><p>{detail.profile.document_code} · نسخه {detail.profile.document_version}</p></div><span className={`rule-status rule-status--${detail.profile.status}`}>{statusLabel(detail.profile.status)}</span></div><div className="rule-governance-strip"><div><small>Scope</small><strong>{detail.profile.scope}</strong></div><div><small>Ruleها</small><strong>{detail.rules.length.toLocaleString('fa-IR')}</strong></div><div><small>Verified</small><strong>{detail.rules.filter(r=>r.verification_status==='verified').length.toLocaleString('fa-IR')}</strong></div><div><small>Activation Gate</small><strong>{ready?'آماده':'ناقص'}</strong></div></div>
 <div className="panel-heading compact"><div><h3>Rule Inventory</h3><small>Profile فعال قابل ویرایش نیست.</small></div>{detail.profile.status==='draft'&&<button className="secondary-button" onClick={()=>setShowRule(v=>!v)}>افزودن Rule</button>}</div>
 {showRule&&detail.profile.status==='draft'&&<form className="rule-profile-form" onSubmit={addRule}><label>Rule Key<input name="ruleKey" required/></label><label>Rule Version<input name="ruleVersion" type="number" min="1" defaultValue="1" required/></label><label>Rule Type<select name="ruleType" required><option value="minimum_strength_mpa">minimum_strength_mpa</option><option value="minimum_strength_ratio_of_fck">minimum_strength_ratio_of_fck</option></select></label><label>Parameters JSON<input name="parameters" required placeholder={'{"minimumMpa":30}'}/></label><label>Reference Clause<input name="referenceClause" required/></label><label>Source Title<input name="sourceTitle" required/></label><label>Source Version<input name="sourceVersion" required/></label><label>یادداشت<input name="notes"/></label><button className="primary-button" disabled={busy}>ثبت Rule</button></form>}
 <div className="rule-table"><div className="rule-table-head"><span>Rule</span><span>Reference</span><span>Verification</span><span>Action</span></div>{detail.rules.map(r=><div className="rule-table-row" key={r.id}><span><strong>{r.rule_key} · v{r.rule_version}</strong><small>{r.rule_type}</small></span><span><strong>{r.source_title} · {r.source_version}</strong><small>{r.reference_clause}</small></span><span><strong>{r.verification_status==='verified'?'Verified':'Unverified'}</strong><small>{r.test_case_count.toLocaleString('fa-IR')} Test Case</small></span><span>{detail.profile.status==='draft'&&r.verification_status!=='verified'?<button className="text-button" disabled={busy} onClick={()=>void verify(r)}>Verify</button>:<b>قفل</b>}</span></div>)}</div>
 <div className="rule-profile-actions">{detail.profile.status==='draft'&&<button className="primary-button" disabled={busy||!ready} onClick={()=>void activate()}>فعال‌سازی و قفل Profile</button>}{detail.profile.status==='active'&&<button className="secondary-button" disabled={busy} onClick={()=>void retire()}>بازنشسته‌سازی Profile</button>}<small>فعال‌سازی تنها وقتی مجاز است که تمام Ruleها Reference، Source Version و Test Case تأییدشده داشته باشند.</small></div></>}</main></div></section>;
}
