import { useEffect, useState } from 'react';
import type { ProjectSummary, SeriesSummary } from '../shared/ipc';
import { isoToPersianLocal } from './jalali';
import './sampling-series-report.css';

type ReportSpecimen={id:string;ageDays:number|null;dueAt:string|null;state:string|null;strengthMpa:number|null;testedAt:string|null;testedBy:string|null;approvedBy:string|null;shape:'cube'|'cylinder'|null;lengthMm:number|null;widthMm:number|null;heightMm:number|null;diameterMm:number|null;massKg:number|null;volumeM3:number|null;densityKgM3:number|null};
type SeriesReport={schema:'tolou-qc-series-report';schemaVersion:number;generatedAt:string;company:{id:string;name:string};organization:{qcManagerName:string;managingDirectorName:string};project:{id:string;name:string;customerName:string;address:string}|null;series:{id:string;sampledAt:string;samplerName:string;title:string;pourId:string|null;pourOccurredAt:string|null;concreteSourceName:string;freshConcrete:{slumpMm:number|null;temperatureC:number|null;measuredAt:string|null};specimens:ReportSpecimen[];summary:{mean7Mpa:number|null;mean28Mpa:number|null;approved7Count:number;approved28Count:number}};notes:string[]};
type SystemBridge={getSeriesReport:(seriesId:string)=>Promise<{ok:boolean;data?:SeriesReport;message?:string}>};
const system=()=>((window as unknown as {tolouSystem:SystemBridge}).tolouSystem);
const n=(value:number|null,digits=2)=>value==null?'—':value.toLocaleString('fa-IR',{maximumFractionDigits:digits});
const stateLabel=(value:string|null)=>value==='approved'?'تأییدشده':value==='draft'?'منتظر تأیید':value==='void'?'باطل':'بدون نتیجه';
const shapeLabel=(row:ReportSpecimen)=>row.shape==='cube'?`مکعب ${n(row.lengthMm,0)}×${n(row.widthMm,0)}×${n(row.heightMm,0)} mm`:row.shape==='cylinder'?`استوانه Ø${n(row.diameterMm,0)}×${n(row.heightMm,0)} mm`:'—';

export function SamplingSeriesReportWorkbench({refreshKey=0,initialProjectId=''}:{refreshKey?:number;initialProjectId?:string}){
 const[projects,setProjects]=useState<ProjectSummary[]>([]),[projectId,setProjectId]=useState(initialProjectId),[series,setSeries]=useState<SeriesSummary[]>([]),[seriesId,setSeriesId]=useState(''),[report,setReport]=useState<SeriesReport|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[exporting,setExporting]=useState(false);
 useEffect(()=>{void window.tolou.listProjects().then(r=>{if(!r.ok)throw new Error(r.message);const active=r.data.filter(p=>p.archived===0);setProjects(active);setProjectId(v=>active.some(p=>p.id===v)?v:(initialProjectId&&active.some(p=>p.id===initialProjectId)?initialProjectId:(active[0]?.id??'')));}).catch(e=>setMessage(e instanceof Error?e.message:'پروژه‌ها بارگذاری نشد'));},[refreshKey,initialProjectId]);
 useEffect(()=>{if(!projectId){setSeries([]);setSeriesId('');setReport(null);return;}void window.tolou.listSeries('customer',projectId).then(r=>{if(!r.ok)throw new Error(r.message);const ordered=[...r.data].sort((a,b)=>b.sampled_at.localeCompare(a.sampled_at));setSeries(ordered);setSeriesId(v=>ordered.some(s=>s.id===v)?v:(ordered[0]?.id??''));setReport(null);}).catch(e=>setMessage(e instanceof Error?e.message:'نوبت‌های نمونه‌برداری بارگذاری نشد'));},[projectId,refreshKey]);
 async function generate(){if(!seriesId)return;setLoading(true);setMessage('');try{const result=await system().getSeriesReport(seriesId);if(!result.ok||!result.data)throw new Error(result.message||'گزارش تهیه نشد');setReport(result.data);}catch(e){setMessage(e instanceof Error?e.message:'گزارش تهیه نشد');}finally{setLoading(false);}}
 async function exportPdf(){if(!report)return;setExporting(true);setMessage('');try{const result=await window.tolou.exportProjectQcPdf(`Tolou-Test-Report-${report.project?.name??'Internal'}-${report.series.id}`);if(!result.ok)throw new Error(result.message);if(!result.data.cancelled)setMessage('PDF رسمی نتیجه آزمون ذخیره شد.');}catch(e){setMessage(e instanceof Error?e.message:'ذخیره PDF انجام نشد');}finally{setExporting(false);}}
 return <section className="panel panel--wide glass series-report-workbench">
  <div className="panel-heading no-print"><div><p className="eyebrow eyebrow--accent">گزارش نتیجه آزمون</p><h3>برگه رسمی یک نوبت نمونه‌برداری</h3></div></div>
  <div className="series-report-controls no-print"><label>پروژه<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">انتخاب پروژه</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>نوبت نمونه‌برداری<select value={seriesId} onChange={e=>{setSeriesId(e.target.value);setReport(null)}}><option value="">انتخاب نوبت</option>{series.map(s=><option key={s.id} value={s.id}>{isoToPersianLocal(s.sampled_at)} — {s.sampler_name}</option>)}</select></label><button className="primary-button" disabled={loading||!seriesId} onClick={()=>void generate()}>{loading?'در حال تهیه…':'نمایش گزارش'}</button>{report&&<button className="secondary-button" disabled={exporting} onClick={()=>void exportPdf()}>{exporting?'در حال ساخت PDF…':'خروجی PDF رسمی'}</button>}</div>
  {message&&<div className="workbench-message no-print">{message}</div>}
  {!report?<div className="recovery-empty no-print"><h3>یک نوبت نمونه‌برداری را انتخاب کنید</h3><p>گزارش فقط از داده‌های واقعی ثبت‌شده همان نوبت ساخته می‌شود.</p></div>:<article className="series-report-sheet" dir="rtl">
   <header className="series-report-header"><div className="series-report-brand"><div className="series-report-mark">T</div><div><p>سامانه طلوع | کنترل کیفیت بتن</p><h2>گزارش نتایج آزمون بتن</h2><strong>{report.company.name}</strong></div></div><div className="series-report-number"><span>شماره گزارش</span><b>{report.series.id}</b><span>تاریخ صدور</span><b>{isoToPersianLocal(report.generatedAt)}</b></div></header>
   <section className="series-report-meta"><div><span>پروژه</span><b>{report.project?.name??report.series.title??'کنترل داخلی'}</b></div><div><span>مشتری / کارفرما</span><b>{report.project?.customerName||'—'}</b></div><div><span>نشانی پروژه</span><b>{report.project?.address||'—'}</b></div><div><span>منبع بتن</span><b>{report.series.concreteSourceName||'—'}</b></div><div><span>تاریخ بتن‌ریزی</span><b>{report.series.pourOccurredAt?isoToPersianLocal(report.series.pourOccurredAt):'—'}</b></div><div><span>تاریخ نمونه‌برداری</span><b>{isoToPersianLocal(report.series.sampledAt)}</b></div><div><span>نمونه‌بردار</span><b>{report.series.samplerName}</b></div><div><span>مسئول کنترل کیفیت</span><b>{report.organization.qcManagerName||'—'}</b></div></section>
   <section className="series-report-summary"><div><small>اسلامپ</small><strong>{report.series.freshConcrete.slumpMm==null?'—':`${n(report.series.freshConcrete.slumpMm,0)} mm`}</strong></div><div><small>دمای بتن</small><strong>{report.series.freshConcrete.temperatureC==null?'—':`${n(report.series.freshConcrete.temperatureC,1)} °C`}</strong></div><div><small>میانگین ۷ روزه</small><strong>{report.series.summary.mean7Mpa==null?'—':`${n(report.series.summary.mean7Mpa)} MPa`}</strong></div><div><small>میانگین ۲۸ روزه</small><strong>{report.series.summary.mean28Mpa==null?'—':`${n(report.series.summary.mean28Mpa)} MPa`}</strong></div></section>
   <section className="series-report-results"><h3>نتایج نمونه‌ها</h3><table><thead><tr><th>ردیف</th><th>سن آزمون</th><th>موعد</th><th>شکل و ابعاد</th><th>جرم kg</th><th>جرم حجمی kg/m³</th><th>مقاومت MPa</th><th>تاریخ آزمون</th><th>آزمایش‌کننده</th><th>وضعیت</th></tr></thead><tbody>{report.series.specimens.map((row,index)=><tr key={row.id}><td>{(index+1).toLocaleString('fa-IR')}</td><td>{row.ageDays==null?'شاهد':`${row.ageDays.toLocaleString('fa-IR')} روز`}</td><td>{row.dueAt?isoToPersianLocal(row.dueAt):'—'}</td><td>{shapeLabel(row)}</td><td>{n(row.massKg,3)}</td><td>{n(row.densityKgM3,0)}</td><td><b>{n(row.strengthMpa)}</b></td><td>{row.testedAt?isoToPersianLocal(row.testedAt):'—'}</td><td>{row.testedBy||'—'}</td><td>{stateLabel(row.state)}</td></tr>)}</tbody></table></section>
   <footer className="series-report-footer"><div><span>تهیه‌کننده / نمونه‌بردار</span><b>{report.series.samplerName}</b><i>امضا</i></div><div><span>مسئول کنترل کیفیت</span><b>{report.organization.qcManagerName||'—'}</b><i>امضا</i></div><div><span>مدیرعامل</span><b>{report.organization.managingDirectorName||'—'}</b><i>مهر و امضا</i></div></footer>
   <div className="series-report-note">{report.notes[0]}</div>
  </article>}
 </section>;
}
