import { useCallback, useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import type { ResultRevision, SampleSummary, SpecimenPhysicsSummary, SpecimenShape, WitnessScheduleRevision } from '../shared/ipc';
import { PersianDateTimeInput } from './PersianDateTimeInput';
import { isoToPersianLocal } from './jalali';

function stateLabel(state: SampleSummary['state']) {
  if (state === 'approved') return 'تأییدشده';
  if (state === 'draft') return 'پیش‌نویس';
  if (state === 'void') return 'باطل';
  return 'در انتظار نتیجه';
}
function persianDate(iso:string|null){return isoToPersianLocal(iso)||'بدون موعد';}

type ActionState={mode:'correction'|'void';row:SampleSummary}|null;
type WitnessAction=SampleSummary|null;
type PhysicsAction={row:SampleSummary;current:SpecimenPhysicsSummary|null}|null;

export function SampleResultsPanel({onChanged,refreshKey=0}:{onChanged:()=>void;refreshKey?:number}) {
  const [rows,setRows]=useState<SampleSummary[]>([]);
  const [reviewRows,setReviewRows]=useState<SampleSummary[]>([]);
  const [physicsRows,setPhysicsRows]=useState<SpecimenPhysicsSummary[]>([]);
  const [history,setHistory]=useState<ResultRevision[]>([]);
  const [witnessHistory,setWitnessHistory]=useState<WitnessScheduleRevision[]>([]);
  const [physicsHistory,setPhysicsHistory]=useState<SpecimenPhysicsSummary[]>([]);
  const [selected,setSelected]=useState('');
  const [selectedWitness,setSelectedWitness]=useState('');
  const [selectedPhysics,setSelectedPhysics]=useState('');
  const [action,setAction]=useState<ActionState>(null);
  const [witnessAction,setWitnessAction]=useState<WitnessAction>(null);
  const [physicsAction,setPhysicsAction]=useState<PhysicsAction>(null);
  const [physicsShape,setPhysicsShape]=useState<SpecimenShape>('cube');
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);

  const physicsBySample=useMemo(()=>new Map(physicsRows.map(item=>[item.sample_id,item])),[physicsRows]);
  const refresh=useCallback(async()=>{
    const [samples,review,physics]=await Promise.all([window.tolou.listSamples(50),window.tolou.reviewQueue(100),window.tolou.listSpecimenPhysics(200)]);
    if(!samples.ok) throw new Error(samples.message); if(!review.ok) throw new Error(review.message); if(!physics.ok) throw new Error(physics.message);
    setRows(samples.data); setReviewRows(review.data); setPhysicsRows(physics.data);
  },[]);

  useEffect(()=>{void refresh().catch((error)=>setMessage(error instanceof Error?error.message:'بارگذاری نمونه‌ها انجام نشد'));},[refresh,refreshKey]);
  useEffect(()=>{if(!selected)return;void window.tolou.resultHistory(selected).then((result)=>{if(result.ok)setHistory(result.data);});},[selected,refreshKey]);
  useEffect(()=>{if(!selectedWitness)return;void window.tolou.witnessScheduleHistory(selectedWitness).then((result)=>{if(result.ok)setWitnessHistory(result.data);});},[selectedWitness,refreshKey]);

  async function openHistory(sampleId:string){setSelected(sampleId);setMessage('');const result=await window.tolou.resultHistory(sampleId);if(!result.ok){setMessage(result.message);return;}setHistory(result.data);}
  async function openWitnessHistory(sampleId:string){setSelectedWitness(sampleId);setMessage('');const result=await window.tolou.witnessScheduleHistory(sampleId);if(!result.ok){setMessage(result.message);return;}setWitnessHistory(result.data);}
  async function openPhysics(row:SampleSummary){setBusy(true);setMessage('');try{const result=await window.tolou.getSpecimenPhysics(row.id);if(!result.ok)throw new Error(result.message);setPhysicsShape(result.data?.shape??'cube');setPhysicsAction({row,current:result.data});}catch(error){setMessage(error instanceof Error?error.message:'بارگذاری مشخصات فیزیکی نمونه انجام نشد');}finally{setBusy(false);}}
  async function openPhysicsHistory(sampleId:string){setSelectedPhysics(sampleId);const result=await window.tolou.specimenPhysicsHistory(sampleId);if(!result.ok){setMessage(result.message);return;}setPhysicsHistory(result.data);}
  async function approve(row:SampleSummary){if(row.state!=='draft'||!row.revision)return;setBusy(true);setMessage('');try{const result=await window.tolou.approveDraft({sampleId:row.id,expectedRevision:row.revision});if(!result.ok)throw new Error(result.message);setMessage(`نتیجه ${row.id} با بازنگری ${result.data.revision.toLocaleString('fa-IR')} تأیید شد.`);await refresh();onChanged();if(selected===row.id)await openHistory(row.id);}catch(error){setMessage(error instanceof Error?error.message:'تأیید نتیجه انجام نشد');}finally{setBusy(false);}}
  async function submitAction(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!action?.row.revision)return;setBusy(true);setMessage('');try{const f=new FormData(event.currentTarget);if(action.mode==='void'){const result=await window.tolou.voidResult({sampleId:action.row.id,expectedRevision:action.row.revision,reason:String(f.get('reason')??'')});if(!result.ok)throw new Error(result.message);setMessage(`نتیجه ${action.row.id} با بازنگری ${result.data.revision.toLocaleString('fa-IR')} باطل شد.`);}else{const testedAt=String(f.get('testedAt')??'');if(!testedAt)throw new Error('زمان آزمون شمسی معتبر وارد کنید');const result=await window.tolou.requestCorrection({sampleId:action.row.id,expectedRevision:action.row.revision,strengthMpa:Number(f.get('strength')),testedAt,testedBy:String(f.get('testedBy')??''),reason:String(f.get('reason')??'')});if(!result.ok)throw new Error(result.message);setMessage(`اصلاح ${action.row.id} به صف Review بازگشت.`);}setAction(null);await refresh();onChanged();if(selected===action.row.id)await openHistory(action.row.id);}catch(error){setMessage(error instanceof Error?error.message:'عملیات نتیجه انجام نشد');}finally{setBusy(false);}}
  async function submitWitness(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!witnessAction)return;setBusy(true);setMessage('');try{const f=new FormData(event.currentTarget);const dueAt=String(f.get('dueAt')??'');if(!dueAt)throw new Error('موعد شمسی معتبر وارد کنید');const result=await window.tolou.scheduleWitness({sampleId:witnessAction.id,expectedRevision:witnessAction.witness_schedule_revision??0,dueAt,reason:String(f.get('reason')??'')});if(!result.ok)throw new Error(result.message);setMessage(`موعد نمونه شاهد ${witnessAction.id} با بازنگری ${result.data.revision.toLocaleString('fa-IR')} ثبت شد.`);const id=witnessAction.id;setWitnessAction(null);await refresh();onChanged();await openWitnessHistory(id);}catch(error){setMessage(error instanceof Error?error.message:'ثبت موعد نمونه شاهد انجام نشد');}finally{setBusy(false);}}
  async function submitPhysics(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!physicsAction)return;setBusy(true);setMessage('');try{const f=new FormData(event.currentTarget);const current=physicsAction.current;const result=await window.tolou.saveSpecimenPhysics({sampleId:physicsAction.row.id,expectedRevision:current?.revision??0,shape:physicsShape,lengthMm:physicsShape==='cube'?Number(f.get('lengthMm')):null,widthMm:physicsShape==='cube'?Number(f.get('widthMm')):null,heightMm:Number(f.get('heightMm')),diameterMm:physicsShape==='cylinder'?Number(f.get('diameterMm')):null,massKg:Number(f.get('massKg')),reason:current?String(f.get('reason')??''):undefined});if(!result.ok)throw new Error(result.message);setMessage(`جرم حجمی ${physicsAction.row.id}: ${result.data.densityKgM3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³`);const id=physicsAction.row.id;setPhysicsAction(null);await refresh();onChanged();await openPhysicsHistory(id);}catch(error){setMessage(error instanceof Error?error.message:'ثبت ابعاد و جرم نمونه انجام نشد');}finally{setBusy(false);}}

  return <section className="panel glass panel--wide">
    <div className="panel-heading"><div><p className="eyebrow">داده زنده SQLite</p><h3>نمونه‌ها و نتایج اخیر</h3></div><div className="row-actions"><span className="count-badge">{rows.length.toLocaleString('fa-IR')}</span><span className="count-badge">Review: {reviewRows.length.toLocaleString('fa-IR')}</span></div></div>
    {message&&<div className="workbench-message" role="status">{message}</div>}
    {reviewRows.length>0&&<div className="history-strip"><strong>صف Review مهندسی</strong>{reviewRows.slice(0,8).map(item=><span key={item.id}>{item.id} · R{item.revision?.toLocaleString('fa-IR')} · {item.reason??'پیش‌نویس جدید'}</span>)}</div>}
    <div className="table-wrap"><table><thead><tr><th>نمونه</th><th>سری / پروژه</th><th>سن / موعد</th><th>مقاومت</th><th>جرم حجمی</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>
      {rows.map(row=>{const physics=physicsBySample.get(row.id);return <tr key={row.id}><td className="mono">{row.id}</td><td>{row.project_name??row.title??row.series_id}<small className="table-subline">{row.series_id}</small></td><td>{row.age_days===null?<><strong>شاهد</strong><small className="table-subline">{persianDate(row.due_at)}</small></>:`${row.age_days.toLocaleString('fa-IR')} روز`}</td><td>{row.strength_mpa===null?'—':`${row.strength_mpa.toLocaleString('fa-IR',{maximumFractionDigits:2})} MPa`}</td><td>{physics?`${physics.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³`:'—'}</td><td><span className={`status ${row.state==='approved'?'status--ok':row.state==='draft'?'status--pending':''}`}>{stateLabel(row.state)}</span></td><td><div className="row-actions"><button className="text-button" disabled={busy} onClick={()=>void openPhysics(row)}>{physics?'اصلاح ابعاد و وزن':'ابعاد و وزن'}</button>{physics&&<button className="text-button" onClick={()=>void openPhysicsHistory(row.id)}>تاریخچه فیزیکی</button>}<button className="text-button" onClick={()=>void openHistory(row.id)}>تاریخچه نتیجه</button>{row.age_days===null&&<><button className="text-button" disabled={busy} onClick={()=>setWitnessAction(row)}>{row.due_at?'تغییر موعد شاهد':'تعیین موعد شاهد'}</button>{(row.witness_schedule_revision??0)>0&&<button className="text-button" onClick={()=>void openWitnessHistory(row.id)}>تاریخچه موعد</button>}</>}{row.state==='draft'&&<button className="primary-button mini-button" disabled={busy} onClick={()=>void approve(row)}>تأیید</button>}{row.state==='approved'&&<button className="text-button" disabled={busy} onClick={()=>setAction({mode:'correction',row})}>اصلاح</button>}{row.state&&row.state!=='void'&&<button className="text-button" disabled={busy} onClick={()=>setAction({mode:'void',row})}>ابطال</button>}</div></td></tr>})}
      {!rows.length&&<tr><td colSpan={7}>هنوز نمونه‌ای ثبت نشده است.</td></tr>}
    </tbody></table></div>
    {physicsAction&&<form className="review-action glass" onSubmit={submitPhysics}><div><strong>ابعاد، جرم و جرم حجمی نمونه</strong><small>{physicsAction.row.id} · {physicsAction.row.age_days===null?'شاهد':`${physicsAction.row.age_days.toLocaleString('fa-IR')} روزه`} · R{(physicsAction.current?.revision??0).toLocaleString('fa-IR')}</small></div><label>شکل نمونه<select value={physicsShape} onChange={(e)=>setPhysicsShape(e.target.value as SpecimenShape)}><option value="cube">مکعبی</option><option value="cylinder">استوانه‌ای</option></select></label>{physicsShape==='cube'?<><input name="lengthMm" type="number" min="0.01" step="0.01" required defaultValue={physicsAction.current?.length_mm??150} placeholder="طول واقعی mm"/><input name="widthMm" type="number" min="0.01" step="0.01" required defaultValue={physicsAction.current?.width_mm??150} placeholder="عرض واقعی mm"/></>:<input name="diameterMm" type="number" min="0.01" step="0.01" required defaultValue={physicsAction.current?.diameter_mm??150} placeholder="قطر واقعی mm"/>}<input name="heightMm" type="number" min="0.01" step="0.01" required defaultValue={physicsAction.current?.height_mm??(physicsShape==='cube'?150:300)} placeholder="ارتفاع واقعی mm"/><input name="massKg" type="number" min="0.001" step="0.001" required defaultValue={physicsAction.current?.mass_kg??''} placeholder="جرم نمونه kg"/>{physicsAction.current&&<input name="reason" required placeholder="علت اصلاح ابعاد یا جرم"/>}<div className="physics-preview"><span>حجم و جرم حجمی توسط موتور محاسباتی محاسبه می‌شود.</span>{physicsAction.current&&<strong>{physicsAction.current.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³</strong>}</div><div className="row-actions"><button className="primary-button mini-button" disabled={busy}>محاسبه و ثبت</button><button type="button" className="text-button" onClick={()=>setPhysicsAction(null)}>انصراف</button></div></form>}
    {witnessAction&&<form className="review-action glass" onSubmit={submitWitness}><div><strong>زمان‌بندی نمونه شاهد</strong><small>{witnessAction.id} · بازنگری فعلی {(witnessAction.witness_schedule_revision??0).toLocaleString('fa-IR')}</small></div><label>موعد آزمون (شمسی)<PersianDateTimeInput name="dueAt" defaultIso={witnessAction.due_at} required /></label><input name="reason" required placeholder="علت تعیین یا تغییر موعد"/><div className="row-actions"><button className="primary-button mini-button" disabled={busy}>ثبت موعد</button><button type="button" className="text-button" onClick={()=>setWitnessAction(null)}>انصراف</button></div></form>}
    {action&&<form className="review-action glass" onSubmit={submitAction}><div><strong>{action.mode==='correction'?'درخواست اصلاح نتیجه تأییدشده':'ابطال نتیجه'}</strong><small>{action.row.id} · R{action.row.revision?.toLocaleString('fa-IR')}</small></div>{action.mode==='correction'&&<><input name="strength" type="number" step="0.01" min="0" required defaultValue={action.row.strength_mpa??''} placeholder="مقاومت MPa"/><label>زمان آزمون (شمسی)<PersianDateTimeInput name="testedAt" defaultIso={action.row.tested_at} required /></label><input name="testedBy" required defaultValue={action.row.tested_by??''} placeholder="انجام‌دهنده آزمون"/></>}<input name="reason" required placeholder={action.mode==='correction'?'علت اصلاح':'علت ابطال'}/><div className="row-actions"><button className="primary-button mini-button" disabled={busy}>ثبت عملیات</button><button type="button" className="text-button" onClick={()=>setAction(null)}>انصراف</button></div></form>}
    {selectedPhysics&&physicsHistory.length>0&&<div className="history-strip"><strong>تاریخچه فیزیکی {selectedPhysics}</strong>{physicsHistory.map(item=><span key={item.revision}>R{item.revision.toLocaleString('fa-IR')} · {item.shape==='cube'?'مکعبی':'استوانه‌ای'} · {item.mass_kg.toLocaleString('fa-IR')} kg · {item.density_kg_m3.toLocaleString('fa-IR',{maximumFractionDigits:1})} kg/m³ · {item.reason??'ثبت اولیه'}</span>)}</div>}
    {selectedWitness&&witnessHistory.length>0&&<div className="history-strip"><strong>تاریخچه موعد شاهد {selectedWitness}</strong>{witnessHistory.map(item=><span key={item.revision}>R{item.revision.toLocaleString('fa-IR')} · {persianDate(item.due_at)} · {item.reason} · {item.entered_by}</span>)}</div>}
    {selected&&<div className="history-strip"><strong>تاریخچه {selected}</strong>{history.map(item=><span key={item.revision}>R{item.revision.toLocaleString('fa-IR')} · {stateLabel(item.state)} · {item.strength_mpa?.toLocaleString('fa-IR')??'—'} MPa · {item.reason??'ثبت اولیه'}</span>)}</div>}
  </section>;
}
